### ISSUE TITLE
Map editor..

### ISSUE THREAD

**Issue by joebgame** [openplanet-nl/openplanet-issues#103]
I don't know if this is an issue with open planet. when I go into the map editor it instantly goes to a black loading screen an goes straight into simple editor. I Verified the game files didn't fix the issue. I unistalled some of the plugins an still the same result..

**Comment by codecat** [comment]
Does it not happen if you disable Openplanet?

> Starting the game without Openplanet:
> 1. Start holding down the Pause/Break key on your keyboard. Don't release it yet!
> 2. Click Play in Ubisoft Connect or the Epic Games Launcher.
> 3. When you see the game itself load (the window opened), release the Pause/Break key now.

**Comment by joebgame** [comment]
I got it fixed. somehow my game setting changed dont know why they did prob
a recent update.. but the quick editor got enable.. thank for checking in..

**Comment by codecat** [comment]
Glad you got it fixed.
