### ISSUE TITLE
Show uploaded file when updateing plugin [admin]

### ISSUE THREAD

**Issue by nitroquery** [openplanet-nl/openplanet-issues#106]
![image](https://user-images.githubusercontent.com/84474400/168171668-8c0e219a-434e-436b-b071-2e399b963f42.png)

**Comment by sylae** [comment]
gonna go ahead and close this, looks like at some point we got this implemented: hitting the download on a plugin version lets you download even if it's in queue

![image](https://github.com/openplanet-nl/issues/assets/2791628/763aeb69-080f-4812-804c-500afe4f54fd)
