### ISSUE TITLE
Automagic settings tooltips do not support line breaks.

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#113]
When using the automagic settings feature, the `description` field (which results in a tooltip in the settings UI) does not support line breaks.
However, implementing a tooltip manually does allow for line breaks. So it seems possible and hopefully easy.

Example usage that would benefit from a line break:

```AngelScript
[Setting category="Appearance" name="Obvious Chat Input" description="When chat input is focused (i.e., you can type a chat msg), this option makes it VERY obvious. Use this option to prevent accidentally being in chat mode at the start of a race."]
bool Setting_ObviousChat = true;
```

Example of a tooltip with a line break:

![image](https://user-images.githubusercontent.com/1046448/170812425-f2a0d988-0d3f-4b6e-971b-40879e797763.png)

Code that does this:

settings: https://github.com/XertroV/tm-never-give-up/blob/5fe8e5b7907751de5c516502e7a3f3d7e84695d0/ngu/SettingsCustom.as#L87
`AddSimpleTooltip` function: https://github.com/XertroV/tm-never-give-up/blob/5fe8e5b7907751de5c516502e7a3f3d7e84695d0/utils/ui.as#L2-L8

**Comment by codecat** [comment]
![image](https://user-images.githubusercontent.com/136534/170823419-1ff17d8a-3c32-4f00-b9b9-db9fcbaa2951.png)

I changed the code to automatically perform word wrapping.
