### ISSUE TITLE
Renaming Plugin name in info.toml does not update until after game restart

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/openplanet-issues#119]
I'm not sure if this is a bug or just a limitation.

Just changing the name of plugin in the `info.toml` file still shows the old name in the logs
![image](https://user-images.githubusercontent.com/90581578/173194907-192b91a9-1ea0-4845-a07b-eded74cc656e.png)

Additionally, after unloading the plugin, the load plugin still retains the old name:
![image](https://user-images.githubusercontent.com/90581578/173194924-3c98853c-a557-417d-9708-a7a51627dcc1.png)

**Comment by chipsTM** [comment]
Ah it takes the folder name for loading plugin. I forgot this

I believe this is just a limitation as the folder cannot be renamed until game is closed (otherwise it's still in use by the runtime)

**Comment by codecat** [comment]
Correct, it's using the plugin ID there, so that it's 100% clear which plugin it is, making it easily identifiable through the filename and website URL. I didn't have any intention of changing this, do you still need something changed here?
