### ISSUE TITLE
Improve UX around access level limitations

### ISSUE THREAD

**Issue by davidbmaier** [openplanet-nl/openplanet-issues#120]
There are three kinds of limitations when it comes to the TM2020 access level, but most of the time it's not clear to the user/player whether a plugin will work on their system/game.

- Unsigned plugins can only be used by Club access players. This is something both Openplanet.dev and the Plugin Manager could communicate better.
- Plugins that use APIs that are only accessible to certain access levels (e.g. custom maps for Standard players). The most common use cases could maybe be identified by automatically or manually going through the code during the review process.
- Plugins that just intentionally restrict access in their code for any other reason. Similarly, this could be detected semi-automatically during the review.

The last two cases aren't as common but still lead to confusion from time to time - but the first case is definitely something that can be solved and needs to be communicated better (only a small minority of the community is aware of what signing is and what it means).

**Comment by codecat** [comment]
The first issue is easily solved, but I'm not sure if this might be a little bit too obnoxious of a banner:

![image](https://user-images.githubusercontent.com/136534/174316624-59169a5a-1cbf-411b-84e4-031ef8a34158.png)

**Comment by davidbmaier** [comment]
It's a little large, but something like that would definitely be better than nothing. 👍
