### ISSUE TITLE
Add `ImGuiHoveredFlags` to `UI::IsItemHovered`

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#121]
Sketch of bug
```AngelScript
void RenderMenuMain() {
  bool open = UI::BeginMenu("blah", false);
  if (UI::IsItemHovered()) { /* Draw tooltip */ }
  if (open) {
    // draw menu stuff
  }
}
```

In this case the tooltip doesn't seem to draw.
If the menu item is enabled then it draws fine.

**Comment by codecat** [comment]
According to [this issue](https://github.com/ocornut/imgui/issues/5088), there's a flag that can be passed to `IsItemHovered`. I'll have to add support for this. 👍
