### ISSUE TITLE
FuncDefs are not documented

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/openplanet-issues#126]
`UI::InputTextCallback@` does not have a documented signature.

Additionally, seems to be some discrepancy as to whether it is `UI::InputTextCallback@` or just `InputTextCallback@`
![image](https://user-images.githubusercontent.com/1596820/174469412-dc6cf696-bc44-4f5a-856f-00e15524bf85.png)

**Comment by Phlarx** [comment]
Same applies to `UI::NodTreeMemberCallback@`

**Comment by XertroV** [comment]
Also `NodTreeMemberCallback@`

**Comment by XertroV** [comment]
I think this is the funcdef for `NodTreeMemberCallback`: `void NodTreeMemberCallback(CMwNod@, Reflection::MwMemberInfo@)
`
https://discord.com/channels/276076890714800129/424967293538402334/953739602886295602

**Comment by XertroV** [comment]
`bool ProcIntercept(CMwStack &in);`
and
`bool ProcInterceptEx(CMwStack &in, CMwNod@)`

**Comment by codecat** [comment]
This will soon appear on the documentation!

![image](https://github.com/openplanet-nl/issues/assets/136534/4185952d-18d7-40ea-9462-5a48f96f7c1d)
