### ISSUE TITLE
Implement support for "strided arrays"

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/openplanet-issues#127]
While researching to get Checkpoint times from Ghosts in Replays (yet unsuccessful unless you race against one in a gamemode), I think that Maniascript takes the checkpoint times there from CTmRaceResultNod::Checkpoints (https://next.openplanet.dev/Game/CTmRaceResultNod)
However, for Openplanet, Checkpoints in an UnknownType, and apparently its a "strided array" which is not supported yet.

**Comment by skybaks** [comment]
Was this added in the most recent openplanet version?

**Comment by codecat** [comment]
Indeed it was!
