### ISSUE TITLE
Create Standardized "Plugin Data" folder 

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/openplanet-issues#128]
It would be nice have a "central" location for Plugin Data, otherwise we can pollute the `OpenplanetNext` data folder (or Openplanet folder for other games)

![image](https://user-images.githubusercontent.com/90581578/174487502-90f26003-1e9a-494c-8225-412043fd50ee.png)

Suggestion is to create a default or idiomatic way of getting to your plugin's data similar to `IO::FromDataFolder()`

`IO::FromPluginDataFolder()` which might point to `OpenplanetNext/PluginData/<plugin identifier>`

**Comment by codecat** [comment]
Wouldn't this be the same as #117?

**Comment by chipsTM** [comment]
Yes pretty much 😅, sorry for the duplicate issue

**Comment by codecat** [comment]
No worries, I appreciate the input regardless! Feel free to re-post your thoughts on the other issue 👍
