### ISSUE TITLE
support dependency versions

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#130]
A significant problem for dependency plugins, IMO, is that dependent plugins cannot specify a version to use. This is critical to avoid breaking changes (alternatively the code from the dependency could just be copied over I guess, but that feels wrong to me).

an alternative solution is to release a new plugin for each breaking change to the dependency's API, though maybe that's gratuitous? It would pollute the plugin list unless there were some special cases added.

**Comment by codecat** [comment]
That would require having multiple versions of a plugin installed (and loaded). I never meant for dependency plugins to be extremely advanced, so I'm going to say no to this for now.
