### ISSUE TITLE
settings erased on compilation failure

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#131]
when a plugin has settings, is reloaded, subsequently fails compilation, and then later updated such that it doesn't fail compilation: settings are reset to default.

It'd be nice if they weren't.

**Comment by XertroV** [comment]
actually, has this already been fixed?

**Comment by XertroV** [comment]
was mb fixed via https://github.com/openplanet-nl/issues/issues/86 ?

IDK, definitely used to have the issue, mb don't have it anymore. Deliberately causing a syntax error does not reset settings.

**Comment by codecat** [comment]
This was fixed for 1.24.0. Not sure if there's a Github issue for it, the one you linked is unrelated.

**Comment by XertroV** [comment]
Settings seem to sometimes be getting wiped still. I've only observed this when there's a script exception that occurs when a script starts (or very shortly afterwards). I was also getting some assertion failures at that time -- hitting 'ignore' didn't crash the game and an exception was printed in the logs. (i was casting something to a `ref` before passing it in to `startnew`, but i forgot that you only cast *from* `ref` on the other end)

using v1.24.4

**Comment by codecat** [comment]
What was the assertion?

**Comment by XertroV** [comment]
![image](https://user-images.githubusercontent.com/1046448/180613704-557ce816-ee8e-4175-b968-504302b89fc3.png)

I get the assertion error if this runs:
`startnew(CoroCacheUrl, cast<ref>(CacheUrl(MakeTmxBgUrlYrMonth(yrMo))));`

but not if this runs:
`startnew(CoroCacheUrl, CacheUrl(MakeTmxBgUrlYrMonth(yrMo)));`

relevant code:
```AngelScript
class CacheUrl {
    string url;
    CacheUrl(const string &in _url) {
        url = _url;
    }
}

void CoroCacheUrl(ref r) {
    string url = cast<CacheUrl>(r).url;
    trace("Caching URL: " + url);
    CheckUrlExistsAndIsCached(url);
}
```
