### ISSUE TITLE
plugin screenshots cropping behavior

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#133]
it'd be nice if screenshots for plugins, when resized, were not cropped (e.g., a black bg or something is added instead, or transparent if png). Example: this screenshot is not as useful as I intended it to be: https://openplanet.dev/imgu/1655435873_f1d469000cb2202a707fbf02678fc0d1d8bb04f5.jpg (original for reference: https://github.com/XertroV/tm-cotd-hud/blob/master/img/qualifying-time-viewer.png)

**Comment by fentras** [comment]
I think if people don't want their screenshots to be cropped automatically, they need to modify them beforehand. I doubt _Openplanet.dev_ will work like _Twitter_ with its AI cropping functionality 😅

What could be done is to add the ability to crop the image before uploading, something like [Cropper.js](https://fengyuanchen.github.io/cropperjs/) can do.

![image](https://user-images.githubusercontent.com/26721650/177040632-1161dc57-dd1d-4f17-b26e-037613532aa1.png)
