### ISSUE TITLE
opening some nods pins cpus 100% + fps drop

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#134]
![image](https://user-images.githubusercontent.com/1046448/175535961-c4fa2294-d144-4a36-87e2-cd6040fec776.png)

Opening "Mobils" (middle bottom of screenshot) pins a core to 100% and causes FPS drops. I guess this is b/c there are 62k items and something like `ListClipper` is not used. closing that tree node restores normality.

**Comment by codecat** [comment]
Unfortunately it's not possible to use ListClipper in Nod Explorer because of variable item heights.
