### ISSUE TITLE
Duplicate ClearColor variables

### ISSUE THREAD

**Issue by fentras** [openplanet-nl/openplanet-issues#137]
In *Trackmania2020* there are duplicate `ClearColor` variables in `Viewport.Cameras[any CHmsCamera]`. In *ManiaPlanet* and *Turbo* the `bool` is named as `ClearColorEnable`, so I suggest to name it the same way in here as well.

#### Trackmania
![Trackmania ClearColor variable](https://user-images.githubusercontent.com/26721650/176444843-2bd1c0bc-9675-4abb-bd61-96e8cc8048d2.png)

#### ManiaPlanet
![ManiaPlanet ClearColor variable](https://user-images.githubusercontent.com/26721650/176445157-77b765c5-d3c1-4275-aea7-c1d84c03939e.png)

**Comment by codecat** [comment]
Thanks :)
