### ISSUE TITLE
Add ImGui colors and styles

### ISSUE THREAD

**Issue by fentras** [openplanet-nl/openplanet-issues#139]
_ImGui_ has lots of great themes that could be applied to the whole _Openplanet_ UI. It would be great to have control over these values.
```angelscript
ImGuiStyle@ style = UI::GetStyle();
style.IndentSpacing = 25;
style.ScrollbarSize = 15;
style.GrabMinSize = 10;

vec4 colors = UI::GetStyle().Colors;
colors[ImGuiCol_Text] = vec4(1.00f, 1.00f, 1.00f, 1.00f);
colors[ImGuiCol_TextDisabled] = vec4(0.50f, 0.50f, 0.50f, 1.00f);
colors[ImGuiCol_WindowBg] = vec4(0.10f, 0.10f, 0.10f, 1.00f);
colors[ImGuiCol_ChildBg] = vec4(0.00f, 0.00f, 0.00f, 0.00f);
colors[ImGuiCol_PopupBg] = vec4(0.19f, 0.19f, 0.19f, 0.92f);
```

Themes could be stored in `.toml` format (so they apply globally on load) like [here](https://github.com/Patitotective/ImThemes/blob/main/themes.toml) and accessed through code like [here](https://github.com/ocornut/imgui/issues/707). Users can create their themes through any available tool out there, like [this](https://github.com/Patitotective/ImThemes) one (or someone could develop it as a plugin).

[![image](https://user-images.githubusercontent.com/26721650/176853732-1e3a617f-4130-46cd-936b-038dba96f273.png)](https://github.com/ocornut/imgui/issues/707#issuecomment-917151020)

**Comment by fentras** [comment]
~~Actually, just realized that it will also solve the problem of implementing your own color palette to match the UI's, like [Plugin Manager](https://github.com/openplanet-nl/plugin-manager/blob/21703c6fa9e221f5897e90841e2d5f5d5178dbc9/src/Interface/Tab.as#L8) does it for tabs right now.~~

**Comment by codecat** [comment]
Not sure what you mean, to match which UI?

**Comment by fentras** [comment]
Whoops, my message is incorrect. I thought that `TabItem` requires explicitly stating the color but I forgot that it has its own default colors and shades can be calculated by just multiplying the value (like in Plugin Manager).

**Comment by codecat** [comment]
This will be added in the next version, but as a `.toml` theme system.
