### ISSUE TITLE
vector swizzles

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#145]
swizzles meaning: `someVec3.xy` sorta thing (for angelscript vectors particularly)

see also: https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Swizzling

limited functionality in this regard is worth it IMO -- e.g., the ability to say `pos.xy` sort of thing.

low priority imo

**Comment by codecat** [comment]
This would be hard to implement dynamically, eg: `xy` or `yx` would have to both be different properties (or virtual properties) because Angelscript doesn't support dynamic properties like that otherwise.

I could however add a few common ones, like `vec3::xy` and `vec4::xyz`
