### ISSUE TITLE
Documentation of `[SettingsTab]` vs `RenderSettings()`

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/openplanet-issues#146]
Since `[SettingsTab]` is more modern and flexible, I think it's safe to call it the preferred form.

However, the docs only describe `RenderSettings()` (here: https://openplanet.dev/docs/reference/plugin-callbacks)
And there is no hint of `[SettingsTab]` anywhere (I would expect it here: https://openplanet.dev/docs/reference/settings)

Additionally, I think the description of `RenderSettings()` should point the reader toward `[SettingsTab]`.

**Comment by codecat** [comment]
The changes in #147 will make this issue more important, and should definitely be somewhere in the documentation.
