### ISSUE TITLE
Allow `[SettingsTab]` to suppress default behavior of `RenderSettings()`

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/openplanet-issues#147]
Since the function name `RenderSettings()` is rather generic, a developer may run into the issue seen here: https://discord.com/channels/276076890714800129/424967293538402334/993045899171352616

I would suggest either (or both):
- a warning / error message to be printed when `RenderSettings()` is itself decorated by `[SettingsTab]`.
- the legacy behavior of `RenderSettings()` (i.e. creating a tab called 'Script') to be suppressed.

**Comment by codecat** [comment]
I will be deprecating the generic `RenderSettings` callback in favor of using `[SettingsTab]`. This means the following changes will be made:

1. Print a deprecation warning when someone uses `void RenderSettings()` **without** any existing `[SettingsTab]` decorated functions
2. If there are **any** `[SettingsTab]` decorated functions, the `void RenderSettings()` callback will not become a callback

This behavior might be confusing if someone is using both a `[SettingsTab]` and `void RenderSettings()` without decorator (as 2 separate functions) but I think that case will be extremely rare.
