### ISSUE TITLE
Add screenshot gallery to plugin page

### ISSUE THREAD

**Issue by fentras** [openplanet-nl/openplanet-issues#150]
Right now when you want to open a screenshot on a [plugin page](https://openplanet.dev/plugin/dashboard) it'll open itself in a new tab. Instead, something like a dedicated gallery (e.g. [lightGallery.js](https://www.lightgalleryjs.com/)) can be utilized to provide a more fluid experience.

![image](https://user-images.githubusercontent.com/26721650/177041072-bed7e2d7-c488-4e64-aa50-9bec713191bf.png)

**Comment by codecat** [comment]
Done for next site deploy 👍 

![image](https://user-images.githubusercontent.com/136534/183134393-91397bb6-b5ed-40fc-8318-3a76f36086bf.png)
