### ISSUE TITLE
Game crashes when hooking into multi-threaded code.

### ISSUE THREAD

**Issue by iLillie** [openplanet-nl/openplanet-issues#151]
I'm hooking into multi-threaded code that is run on rendering, and crashes with error Assertion Failed on expression: "tld && tld->activeContexts[tld->activeContexts.GetLength() - 1] == ctx"

**Comment by iLillie** [comment]
Error window: 
![error](https://user-images.githubusercontent.com/75392499/177041238-5aa6056d-58b2-48db-8128-481e8b0a7c47.png)

**Comment by codecat** [comment]
Easiest way to solve this would be for me to lock a (recursive) mutex for each script execution.

**Comment by codecat** [comment]
I've made hooking into multithreaded code a little bit safer, but it's still not 100% guaranteed to be safe, particularly when using API's exposed by the game or by Openplanet. At the very least, this assertion should no longer show.
