### ISSUE TITLE
Add flag to enable Docking for a single window

### ISSUE THREAD

**Issue by fentras** [openplanet-nl/openplanet-issues#152]
Currently you can either enable _Docking_ (Openplanet > Settings > General > Enable window docking) for all windows or disable completely. For some windows it would be a really handy feature (especially to avoid implementing your own features, like making a window resize to full screen). Several solutions can be introduced into `UI` namespace:
- `bool UI::IsDockingEnabled()` method checks if _Docking_ global setting is enabled
- `enum UI::WindowFlags::ForceDocking` flag that will enable _Docking_ for a window even if the global setting is disabled
  - Can be docked to full screen, sides, etc.
  - Windows with the same flag can dock in each other

![image](https://user-images.githubusercontent.com/26721650/177041861-e53962af-ca88-40c2-8c41-d83295c750e2.png)

**Comment by codecat** [comment]
I have added `UI::IsDockingEnabled()`. I don't think it's possible to force a window to have docking enabled, that would have to be implemented upstream in imgui itself.

Although I have been thinking about enabling docking with the shift key by default, as per #166, but I will close this for now.
