### ISSUE TITLE
Reflection for `enum`

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/openplanet-issues#153]
Allowing for checking if a value is a defined enum value, retrieving the list of all defined values, etc.

**Comment by codecat** [comment]
Wouldn't this tie in with #48?

**Comment by Phlarx** [comment]
I read #48 as different; it is specifically asking for a `typeof` procedure, which does not solve the issue here.

(I would expect `typeof(VirtualKey(7))` would return `VirtualKey` despite the fact that no virtual key is assigned to 7.)

Depending on your interpretation of the scope of these issues, you could reasonably consider them duplicates.

**Comment by codecat** [comment]
I see that issue as an umbrella issue for anything reflection, so I'll close this as duplicate of #48.
