### ISSUE TITLE
Add support for Images and Code blocks in `UI::Markdown()`

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/openplanet-issues#160]
The NadeoServices helper plugin will use massively UI::Markdown for documentation about routes. But images and code blocks are not supported on this method. Would be useful to have support with it.

My priority for this plugin is code blocks. Images would be useful for the plugin manager or the maniaexchange plugin

**Comment by codecat** [comment]
I have added support for code blocks. Images will have to wait for a bit though.

**Comment by codecat** [comment]
Closing this for now.. if you really need images please open a new issue 👍
