### ISSUE TITLE
`IO::FromDataStorage` doesn't recursively create folders

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#161]
I'm making this issue because the following behavior isn't what I expected based on e.g.: 

> The necessary folders are automatically created when calling IO::FromStorage.

([source](https://github.com/openplanet-nl/issues/issues/117#issuecomment-1179782398))

Documented example w/ workaround:

```AngelScript
// this works, the necessary folders are created:
string rootFilePath = IO::FromStorageFolder("rootFile.txt");

// trying to open this path fails because the `jsonFiles` folder is not created:
string jsonFilePath = IO::FromStorageFolder("jsonFiles/file2.json");
/* Fails:
Json::ToFile(jsonFilePath, Json::Object());
*/

/* a simple workaround (for the plugin dev) is just to call `CreateFolder`
   recursively on whichever folder needs creating */
IO::CreateFolder(IO::FromStorageFolder("jsonFiles/"), true);
// now we can read/write to `jsonFilePath`;
```

**Comment by codecat** [comment]
Yeah, I guess the documentation is a little misleading. The documentation means that the `PluginStorage/Plugin` folder is automatically created, not any sub-folder.

**Comment by XertroV** [comment]
Misleading feels like a strong word, but I agree with ambiguous or unclear. I think I was probs a bit biased, too, since I'd been working on folder hierarchy stuff and considering when/how to create subfolders etc. (So I had a different idea of what 'necessary' meant.) It's not a difficult problem (for a plugin dev) to solve in any case.
