### ISSUE TITLE
calling `PreloadImage(string ImageUrl)` crashes the game (TM2020)

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#163]
PreloadImage is a method of https://next.openplanet.dev/Game/CGameManialinkScriptHandler

IDK if this is maybe just an API thing? (Like maybe it's a wstring instead of a string)

I'm calling it on `app.MenuManager.ManialinkScriptHandlerMenus`

**Comment by codecat** [comment]
It's likely crashing because `CGameManialinkScriptHandler::Page` is null.
