### ISSUE TITLE
'Scripts' menu overlaps with Openplanet bar when list is full

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/openplanet-issues#167]
When you have a lot of items in the scripts menu, the list overlaps with the Openplanet toolbar

![image](https://user-images.githubusercontent.com/42576124/182671962-9a0f79cd-2712-4588-ae59-8f88b4ebfecc.png)

The problem is when you click on the 'Scripts' menu it also clicks on the first item instantly (here the Shoubox), so you had to click at the very top of the button

**Comment by codecat** [comment]
This would probably be something for ImGui upstream. There might be an existing Github issue for it there.
