### ISSUE TITLE
Add a option in info.toml to not load the plugin on game startup 

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/openplanet-issues#168]
I would like to add a option on the info.toml file to not load the plugin on game startup and keeps unloaded until we load trough the "Developer" menu

**Comment by codecat** [comment]
For what purpose?

**Comment by GreepTheSheep** [comment]
Plugins that might cause game crash during development

**Comment by codecat** [comment]
I'm not sure I see a good reason to have this implemented still. If you have a reproducable crash related to Openplanet, feel free to report it. Otherwise, I'd recommend making a menu option if you're testing something that might crash the game.
