### ISSUE TITLE
Allow changing icon of scripted tab

### ISSUE THREAD

**Issue by nbeerten** [openplanet-nl/openplanet-issues#170]
Allow changing the icon of scripted tabs (SettingsTab) to something different than the current `</>` icon. Altough this would remove the indication that it's a scripted tab, it would make navigation easier with proper icons meant for specific actions and categories.

**Comment by codecat** [comment]
This will be implemented in the next update!

![image](https://user-images.githubusercontent.com/136534/185761433-a577b0de-aa58-44a0-8691-a8729203953a.png)
