### ISSUE TITLE
json handle weirdness

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#181]
Stemming from a discussion on discord WRT JSON handles not working right.

For example:

```angelscript
auto t = Json::Object();
t['inner'] = Json::Object();
t['inner']['value'] = 1337;
print(Json::Write(t)); // as expected
auto inner = t['inner'];
inner['value'] = 999;
print(Json::Write(t)); // as expected
t['inner'] = Json::Object();
t['inner']['deliberate'] = 'yes';
print(Json::Write(t)); // as expected
print(Json::Write(inner)); // !? {"deliberate": "yes"}
t['inner'] = inner;
print(Json::Write(t)); // {"inner":{}}
```

Discord link: https://discord.com/channels/276076890714800129/424967293538402334/1023887684894212149

I copied the discord log here for posterity but the formatting is bad.

> 3:05 PM]XertroV: I don't understand what's going on with this -- any explanation appreciated:
> auto chs = data.j['challenges'];
> chs['maxId'] = 123;
> print(Json::Write(chs)); // `{"maxId": 123}`
> print(Json::Write(data.j['challenges'])); // `{maxId: 123}`
> data.j['challenges'] = chs;
> print(Json::Write(data.j['challenges'])); // `{}`
> 
> The reason for this pattern was to accommodate the old way of doing json.
> Apparently I can just omit data.j['challenges'] = chs;, but this doesn't seem like the right behavior.
> (Note: output from the print statements is in a comment next to the line but it's hard to see) (edited)
> [3:08 PM]XertroV: There are so many issues with the COTD_HUD json stuff that they're all obfuscating one another. Some queues and DBs wiped too b/c old behavior worked but new behavior just returns like 'null' or something trivial. :(
> But all the DB code I generated with my codegen util is fine, so that's nice.
> [3:16 PM]XertroV: Even weirder:
>         auto t = Json::Object();
>         t['inner'] = Json::Object();
>         t['inner']['value'] = 1337;
>         print(Json::Write(t)); // as expected
>         auto inner = t['inner'];
>         inner['value'] = 999;
>         print(Json::Write(t)); // as expected
>         t['inner'] = Json::Object();
>         t['inner']['deliberate'] = 'yes';
>         print(Json::Write(t)); // as expected
>         print(Json::Write(inner)); // !? {"deliberate": "yes"}
>         t['inner'] = inner;
>         print(Json::Write(t)); // {"inner":{}}
> 
> it's like json objects are virtual representations of their path relative to a root object.
> [4:30 PM]Phlarx: At first glance, I'd guess it's because t and inner are both reference types: Json::Value@... though I'd have to be less tired to understand why exactly
> XertroV
> There are so many issues with the COTD_HUD json stuff that they're all obfuscating one another. Some queues and DBs wiped too b/c old behavior worked but new behavior just returns like 'null' or something trivial. :( But all the DB code I generated with my codegen util is fine, so that's nice.
> [5:36 PM]XertroV: General FYI: I have COTD_HUD working again I think. Once I realized that i needed not to re-set any json objects, it was okay (did a bunch of type conversions and things earlier when I wasn't sure what to change).
> @Phlarx
> At first glance, I'd guess it's because t and inner are both reference types: Json::Value@... though I'd have to be less tired to understand why exactly
> [5:39 PM]XertroV: Yeah, but surely this isn't the right behavior for other objects/references.
> 
> The docs refer to json values as a 'tree' and I think I'm getting it more, now. For example:
> auto root = Json::Object();
> auto jsonInATree = root['edge1'];
> print(Json::Write(jsonInATree)); // should print null
> root['edge1'] = Json::Array();
> root['edge1'].Add(1234);
> print('' + int(jsonInATree[0])); // should print 1234
> 
> 
> This is... not how I would expect many other things to work.
> @XertroV
> I don't understand what's going on with this -- any explanation appreciated: auto chs = data.j['challenges']; chs['maxId'] = 123; print(Json::Write(chs)); // `{"maxId": 123}` print(Json::Write(data.j['challenges'])); // `{maxId: 123}` data.j['challenges'] = chs; print(Json::Write(data.j['challenges'])); // `{}` The reason for this pattern was to accommodate the old way of doing json. Apparently I can just omit data.j['challenges'] = chs;, but this doesn't seem like the right behavior. (Note: output from the print statements is in a comment next to the line but it's hard to see) (edited)
> [7:24 PM]Miss:
> data.j['challenges'] = chs;
> print(Json::Write(data.j['challenges'])); // `{}`
> 
> This looks like a bug to me, because j["challenges"] is already the handle of chs
> @Miss
> data.j['challenges'] = chs; print(Json::Write(data.j['challenges'])); // `{}` This looks like a bug to me, because j["challenges"] is already the handle of chs
> [8:10 PM]XertroV: yeah, it only happens (AFAIK) when you do:
> x = json['key'];
> json['key'] = x;
> 
> So, while it's a questionable pattern, it's not what I'd expect from vanilla handles, e.g.:
> class A {}
> class B { A a; }
> B b = B();
> A@ _a = b.a;
> @b.a = _a;
> [8:10 PM]Miss: Yes, can you report it?
> [8:11 PM]XertroV: yup -- openplanet/issues I assume
> NEW
> [8:11 PM]Miss: Yes

**Comment by codecat** [comment]
This is due to the optimization of handles being handles. Take for example the following Angelscript code:
```asc
class @Foo {
  array<int> m_numbers;

  void CopyFrom(Foo@ other) {
    m_numbers.RemoveRange(0, m_numbers.Length);
    m_numbers.InsertAt(m_numbers.Length, other.m_numbers);
  }
}

void Main() {
  Foo@ a = Foo();
  a.m_numbers.InsertLast(123);
  a.CopyFrom(a);
}
```
The call to CopyFrom will first clear the number array before adding the items to itself. Because the object being copied from is the same object that we're copying to, we are now clearing both the source and destination, causing our object to be cleared.

I fixed this:
```asc
auto js = Json::Parse("{\"a\":{\"b\":1}}");
js["a"] = js["a"];
print(Json::Write(js));
```
Which will now print `{"a":{"b":{"c":1}}}`.

But this doesn't fix all of such cases, for example the following code:
```asc
auto js = Json::Parse("{\"a\":{\"b\":{\"c\":1}}}");
js["a"]["b"] = js["a"];
print(Json::Write(js));
```
Will print `{"a":{"b":{"b":{}}}}`.

To solve this correctly, a (second) copy will have to be made of the object that we're copying from, which wouldn't be the best idea for performance in certain situations. It might be best to eventually add some kind of `CopyFromSelf` or some other (better named?) solution. I'll close this for now because I think self-assignments ought to be rather rare.

**Comment by XertroV** [comment]
Thx, that makes sense now.

> I think self-assignments ought to be rather rare.

I agree, the only reason I was doing it before was to work-around issues w/ the previous json implementation.
