### ISSUE TITLE
CTD on expanding (certain?) CGameItemModel nod

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/openplanet-issues#182]
Repro steps:
- Open Stadium.pak in the Pack Browser
- Navigate to Nod Stadium/Items/ObstaclePusher4m.Item.Gbx
- Preload and load the Nod
- Try to expand the tree in the Nod explorer tab

**Comment by codecat** [comment]
This was because `CPlugGameSkinAndFolder` has its own `IdName` field with a different type, which was causing Nod Explorer to get the wrong field for the wrong type. Fixed for next update.
