### ISSUE TITLE
Insufficient permissions, Can't use plugins even though I have the advanced editor

### ISSUE THREAD

**Issue by dextruax** [openplanet-nl/openplanet-issues#183]
I have the advanced editor from having standard access last year, but the plugins have Insufficient permissions when I try to use them.
![Trackmania2022-9-27-17-12-39](https://user-images.githubusercontent.com/114532834/192639031-4f30ff84-e95e-4f64-9a31-f0f34a71fb7d.jpg)

**Comment by codecat** [comment]
I fixed the `Plugin_EditorDeveloper` plugin showing this error. 👍
