### ISSUE TITLE
Has `InterceptProc` broken for blocking calls?

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#184]
All* intercepted procs that I block cause ML issues now, when they didn't before. IDK if that's due to a nadeo change, but could it be due to the new performance metrics for blocked procs?

[*]: I think it's all procs. I can't think of any that aren't affected.

**Comment by codecat** [comment]
I'll push a possible fix for this to edge, hopefully you can let me know if that works.

**Comment by XertroV** [comment]
Seems to work
