### ISSUE TITLE
Missing enum? `CGameManiaAppScriptEvent::EType::32759`

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#186]
MLHook intercepts a menu event with type `CGameManiaAppScriptEvent::EType::32759` (via `tostring(event.type)`).

Events of this type have `event.MenuNavAction` set to `32759`, too (even tho they're different enums)

**Comment by XertroV** [comment]
Note: this is also the case for `CGameManiaAppPlaygroundScriptEvent::EType::32579` (which is one of the only playground script events I intercept, maybe the only type)

**Comment by codecat** [comment]
This sounds like uninitialized memory, is this in any way related to #185?

**Comment by XertroV** [comment]
This morning the number has changed to 32758: 
![image](https://user-images.githubusercontent.com/1046448/193181671-8776e945-b038-46d3-b924-928e3cd65c49.png)

> This sounds like uninitialized memory, is this in any way related to https://github.com/openplanet-nl/issues/issues/185?

I don't think so; the `.Type` field should be defined on all events since it's the first thing that is always checked by ML. After that only specific properties are checked.
Warnings are sometimes emitted for checking the wrong fields (e.g., `.KeyCode` on a not-`KeyPress` event) but those events aren't the ones that cause a crash as in #185.

**Comment by codecat** [comment]
Will close this, because I don't think this is related to Openplanet itself.
