### ISSUE TITLE
nod explorer crash via `ExploreNod` calls

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#187]
I ran into this through using MLHook's UILayers Browser. 

1. In playground open a PG UILayer via ExploreNod (like, should be opened in a new tab)
2. close nod explorer
3. exit playground
4. open nod explorer
5. crash

**Comment by codecat** [comment]
This is not a bug - the nod is no longer valid, so displaying it will cause a crash. There is nothing I can realistically do about this.

**Comment by XertroV** [comment]
Ah okay. I was hoping there was something you could check for on the backend.
