### ISSUE TITLE
Add other methods of plotting (like ImPlot)

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/openplanet-issues#200]
currently, the only IMGUI-comptaible way to easily make plots is UI::PlotLines. However, one can quickly reach the limits of it when it comes to customization. Getting rid of the default tooltip is managed by pushing text and popup backgrounds to be invisible, for example.
Adding a more customizable plotting method could make things like these easier.
Suggestion by Miss: https://github.com/epezent/implot

**Comment by skybaks** [comment]
+1 to this request. I could really benefit from implementation of more sophisticated plotting tools. Especially if the school mode is going in soon, this could really help keep from everyone reimplementing their own plotting functions in nvg

**Comment by codecat** [comment]
Good point about the new mode indeed.
