### ISSUE TITLE
TM2020: viewing `Editor.PluginMapType` shows `assertion failed: sizeof(T) < sizeof(val)`

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#201]
TM2020: viewing `Editor.PluginMapType` shows `assertion failed: sizeof(T) < sizeof(val)`

IDK if this is an openplanet issue (or a nadeo one) but a few things crash openplanet via nodexplorer under the editor, so thought it was worth noting.

**Comment by codecat** [comment]
I think this is a duplicate, and is already fixed.
