### ISSUE TITLE
`Text::Format` doesn't do 64 bit integers correctly

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#204]
`Dev::ReadUInt64` and `Dev::GetOffsetUint64` only read 4 bytes

Example on discord: https://discord.com/channels/276076890714800129/424967293538402334/1040188092776198144

**Comment by XertroV** [comment]
I think this might actually be a bug with `Text::Format`;
Demo: `print(Text::Format("%x", uint64(-1)) + ", " + uint64(-1));`

**Comment by codecat** [comment]
What about `Text::Format("%llx", uint64(-1))`?

**Comment by XertroV** [comment]
> What about Text::Format("%llx", uint64(-1))?

That results in `"ffffffffffffffff"`. One `l` outputs `ffffffff`, the same as no `l`s.

Okay, well i guess this makes sense. It's not intuitive b/c the input var is a uint64.
Feel free to close if this is what you'd expect. (Maybe we could add something to the docs?)

**Comment by codecat** [comment]
Yes, this would indeed be good to have in the docs. Although, considering #176 we might want to eventually move to something else.. maybe there's something less low level we can use here. Will close this for now.
