### ISSUE TITLE
socket reuse hangs indefinitely

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#207]
reusing a socket after calling `.Close()` can cause arbitrarily long hangs. I'm not sure why, but TM becomes unresponsive (but music plays still) and restarting the *server* is a way to fix. (That triggers an execution timeout on the openplanet side.) From what I can tell, the socket acts like it reconnects successfully (and the server sees this) but the socket hangs indefinitely on attempting a read (or mb on checking `.Available()`).

Simply initializing a new socket fixes this issue.

IMO it'd be nice to just throw an error on socket reuse so that ppl in future don't have to debug it. (Or a warning for backwards compatibility mb)

**Comment by codecat** [comment]
I can't reproduce this on the socket refactoring I've done today, so I'm assuming this is fixed. Let me know if this isn't the case when the `edge` build is out with these changes.
