### ISSUE TITLE
plugin urls oddity

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#208]
useragent filtering on openplanet.dev apparently doesn't work for plugins that don't exist. Example: via `curl https://openplanet.dev/plugin/$id > op-$id.html` for some `$id` (0 bytes when the plugin exists, 5kb otherwise)

Also, using the ID of a plugin in a url will redirect anon users to a url including the plugin-id-name of the plugin even if the plugin is unreleased.

**Comment by codecat** [comment]
The first issue you mention is the expected behavior, because `curl` doesn't follow the redirect for you. You need to use `curl -L` for it to follow the redirect.

I have fixed the second issue for the next site update. 👍
