### ISSUE TITLE
Camera Position Sometimes Bugged

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#209]
I noticed yesterday that `Camera::GetCurrentPosition()` is sometimes bugged such that static coords are returned. I don't know what they correspond to. Yesterday, the coords were (0, 1, -8.5). I first observed it on my dev server with like 64 bots, but later it happened in TOTD (the NFS tribute map).

In the bugged state you can use minimap to see the camera position. Usually it's not even on the grid.

Not sure how to reproduce. It seemed to persist until I changed server. (Even rejoining the same server did not fix)

**Comment by ArEyeses79** [comment]
If I open a map from main menu (using a plugin such as tmx or bingo), the camera position is <0, 0, 0>.
If I am in a map, or even just click the 'play' button, then when I open a map with a plugin camera works correctly
(I don't know if this is caused by the same bug as XertoV's issue, it might be)

**Comment by XertroV** [comment]
So, when this happens for me, `app.Viewport.Cameras` has 3 cameras, rather than the usual 2.
In this case, it looks like the 0th camera is the bugged one.

I think this is due to the way `Camera::` chooses which cam to use, particularly due to the backwards for loop (meaning the 0th camera, if a valid selection, will always be selected).

When there are 2 cameras, every case I've seen has the same position, velocity, etc values. Since this is sufficient for `Camera::` (afaik), a patch might be to just use the camera in position `Cameras.Length - 1` (or `- 2`). 

Or, replace `@g_currentCamera = camera;` with `@g_currentCamera = camera; break;`.

#### cam 0

![image](https://user-images.githubusercontent.com/1046448/214788260-fe500c80-e124-47ad-89ba-897469b1d751.png)

### cam 1

![image](https://user-images.githubusercontent.com/1046448/214788321-37d310f1-f828-4436-92a1-68f272dbd73b.png)

### cam 2

![image](https://user-images.githubusercontent.com/1046448/214788370-db88c117-85a2-486b-aaee-774b2cc6379a.png)

**Comment by codecat** [comment]
I think the `break;` makes sense actually.
