### ISSUE TITLE
Latest TM update makes the game crash when trying to open specific Scene Explorer

### ISSUE THREAD

**Issue by bmx22c** [openplanet-nl/openplanet-issues#218]
Hi,
After the latest game update (14/12/2022), with Openplanet 1.25.21, if you open the Scene Explorer in the main menu (the new one), and go into
`Menu manialinks > (17th one) > CGameManialinkFrame > #frame-global > [crash]`
it'll crash

**Comment by XertroV** [comment]
Happens for me, too

**Comment by nan-inf** [comment]
Still an issue with the 2023-01-18 update. Also, it seems to happen with every `#frame-global` that has children (at least the few I tried, I got tired of constantly restarting the game after that).
