### ISSUE TITLE
Camera::ToScreen in replay editor when not fullscreen

### ISSUE THREAD

**Issue by ArEyeses79** [openplanet-nl/openplanet-issues#221]
The position returned from Camera::ToScreen (and I expect also Camera::ToScreenSpace) always assumes that the camera window takes up the whole screen, but in replay editor this is not always the case.

**Comment by codecat** [comment]
Hmm I wonder if there's a good way to get the actual 3D viewport dimensions & position in every case. 🤔

**Comment by XertroV** [comment]
> Hmm I wonder if there's a good way to get the actual 3D viewport dimensions & position in every case. 🤔

I think this is a good way to do it. (and much of the work is already done!)

`CHmsCamera` has the properties `DrawRectMin` and `DrawRectMax`, similar to `CHmsZoneOverlay` (though it is called `m_DrawRect_min` and `m_DrawRect_max`) and `CScene2d` (`OverlayMin` and `OverlayMax`).

You can observe that DrawRectMin/Max do directly control the camera to screen space mapping by editing them in the nod explorer.

Editor UI Toolbox already converts between these values and screen space. (Though, my matrix-related code might not be that efficient or elegant): https://github.com/XertroV/tm-editor-ui-toolbox/blob/master/src/Main.as#L263-L272

Hope this helps.

**Comment by XertroV** [comment]
Heres some code that draws an orange border around the camera view (e.g., in media tracker). The coord system for DrawRectMin/Max has like (-1,-1) in the bottom right and (1, 1) in the top left.

```angelscript
    void ShowShotPreviewOutline() {
        auto cam = Camera::GetCurrent();
        vec2 screen = vec2(Draw::GetWidth(), Draw::GetHeight());
        vec2 uvTL = vec2(-cam.DrawRectMin.x, -cam.DrawRectMax.y);
        vec2 uvBR = vec2(-cam.DrawRectMax.x, -cam.DrawRectMin.y);
        vec2 tlCam = (uvTL / 2. + vec2(.5, .5)) * screen;
        vec2 brCam = (uvBR / 2. + vec2(.5, .5)) * screen;
        vec2 pos, size;
        pos = tlCam;
        size = brCam - tlCam;
        // draw a rectangle over the MT camera view to aid map positioning.
        nvg::Reset();
        nvg::BeginPath();
        nvg::Rect(pos, size);
        nvg::StrokeColor(vec4(.9, .5, 0, .9));
        nvg::StrokeWidth(Draw::GetHeight() / 150.);
        nvg::Stroke();
        nvg::ClosePath();
    }
```

![image](https://user-images.githubusercontent.com/1046448/210668913-ad3ce595-4cf9-4fee-9216-cb04fb0b3bd5.png)
