### ISSUE TITLE
Some procs have duplicate entries in nod explorer

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#222]
Not sure if this is really an issue or not, but seems anomalous.

Here is a screenshot of some procs from `GetApp().Editor.PluginMapType.Camera` (TM2020).
You'll notice that many of them are duplicates. Some of these, like `Watch` take different arguments (which I guess is fine). Though, the variants of at least one, `Look`, appear to take the same arguments. These duplicate entries don't appear in <https://next.openplanet.dev/Game/CGameEditorPluginCameraAPI> (mb because it's generated before the latest version of openplanet and/or the latest update).

![image](https://user-images.githubusercontent.com/1046448/210314420-deabadc4-2a5e-4321-8248-889ce3a74e91.png)

(Note: initially i thought more procs were duplicated, but this is actually the only one I found upon reinspection)

For context, this looks very similar to `Watch` in the nod explorer, but the argument type is different for each of the procs: 
![image](https://user-images.githubusercontent.com/1046448/210314632-b268fb1a-04d9-4661-bb46-c5118612844d.png)

**Comment by codecat** [comment]
These are actually different procs with different parameters:
```cpp
void Look(CGameEditorPluginMap::ECardinalDirections8 Direction);
void Look(CGameEditorPluginMap::ECardinalDirections8 Direction, bool Smooth);
void Look(CGameEditorPluginMap::ECardinalDirections Direction);
void Look(CGameEditorPluginMap::ECardinalDirections Direction, bool Smooth);
```
