### ISSUE TITLE
OpenplanetNext.json is invalid (ish) json: duplicate keys

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#223]
Some functions/procs like `Watch` from `CGameEditorPluginCameraAPI` are in the json as members of an object where the key name is the function name. Since the function name is re-used for multiple, overloaded functions, this means JSON parsers don't correctly read the json spec.

Related: https://github.com/openplanet-nl/issues/issues/222

**Comment by codecat** [comment]
The new format will be an array of objects, where the key `n` is the name of the member, which can now be duplicate.

![image](https://user-images.githubusercontent.com/136534/213743448-66041870-2033-46b2-895a-9501d2473255.png)

**Comment by XertroV** [comment]
@codecat Could you also add a version flag near the root please? That will just make it easier on my end WRT parsing (particularly: so that I can support both at once without worrying much, so it just works).

**Comment by codecat** [comment]
Sure, I've added an `op` key to the root with the Openplanet version number.
