### ISSUE TITLE
Crash (instead of error) when passing nan as size to nvg::Circle

### ISSUE THREAD

**Issue by ArEyeses79** [openplanet-nl/openplanet-issues#224]
I don't know if this also happens with other nvg functions.
I get a C++ runtime error popup, and the game crashes.

**Comment by codecat** [comment]
I'll make some protections for this, plus I have requested a feature on the Angelscript forum: https://www.gamedev.net/forums/topic/713618-add-hint-that-float-cant-be-nan-or-inf/
