### ISSUE TITLE
More swizzles please

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#227]
These swizzles would be useful:

* `.xy`, `.zw` on `vec4`
* `.xz`, `.zx`, `.yx`, `.yz` on `vec3`
* `.yx` on `vec2`

I find myself doing things like `aVec4.xyz.xy`, or having to manually construct them like `b = vec2(a.z, a.w)`

it would also be nice if we had shortcuts like `vec4(1)` to populate all fields of the vector with the provided float.

I really liked how vectors work in GLSL. I think all combinations of all sizzles are available, e.g., stuff like `.xxy` or `.zxy`, which is also nice but mb not worth the effort in this case (unless you can like macro it).

**Comment by codecat** [comment]
Having the different swizzles is cool, but I think it will make people expect every possible combination to work (especially on vec4). I might implement the in-order swizzles at the very least:

* `xy`, `xyz`, `yz`, `yzw`, `zw` on `vec4`
* `xy`, `yz` on `vec3`

Anything out of order would introduce way too many alternative functions, imo. (Which all will display in the documentation, as well!)

The single `vec4(1)` is a good idea, and I thought I had it actually but I guess not.

**Comment by XertroV** [comment]
Sounds like a good compromize -- the out of order ones are much less useful unless using vecs as general storage for floats/ints. Which is probs not great practice with plugins (compared to shaders).
