### ISSUE TITLE
Optimize `UI::LoadFont` when fonts loaded on the same frame

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#233]
Currently, if I try to load multiple (12) fonts at once, outside initial load and after lots of other fonts have been loaded, the plugin times out. (Hit's my limit of 4000ms)
This does not happen on initial load, however.

The currently available solution to this (for plugin devs) is to `yield` between each load. Which makes the font atlas reload time painfully apparent.

However, the fact that this is a problem suggests that the font atlas is being rebuilt after each font is loaded. This is something that can be controlled on the openplanet side.

My suggestion is that when `UI::LoadFont` is called, it loads the font (via `AddFontFromFileTTF`) but does not immediately call `io.Fonts->Build()` (or, alternatively, `ImGui_ImplXXXX_DestroyFontsTexture` and then `ImGui_ImplXXXX_CreateFontsTexture`), but instead marks the font atlas dirty on the openplanet side. Then, before `ImGui::NewFrame`, if a font has been loaded, then openplanet should call the aforementioned functions. (Note: I found the destroy/create method more reliable, and the create method calls `io.Fonts->Build()` anyway, so seems like the better way to go if that isn't how it is already.)

This would, by my estimate, take approx the same time as loading one font, but you get to load as many as you want.

**Comment by XertroV** [comment]
This sort of technique might be able to be used during initialization, too, to batch font loading during the plugin load and initialize phase.

**Comment by codecat** [comment]
I think it calls `Build` on purpose because rendering fonts isn't possible in that "limbo" state, and some plugins were doing The Wrong Thing that caused some assertions. Maybe I'll have to re-evaluate though.

**Comment by codecat** [comment]
This is not a trivial task to solve for several reasons. I'd rather wait for ImGui to improve its font code - there's some great stuff in the works!
