### ISSUE TITLE
Improve support for ImGui glyph ranges

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#234]
Note: this may synergize with https://github.com/ocornut/imgui/pull/3761 which is slated for inclusion in imgui v1.90: https://github.com/ocornut/imgui/milestone/14

This is a request for better support for glyph ranges. As an example, https://github.com/ocornut/imgui/pull/5747/files is an imgui PR to add support for some glyph ranges, and the ranges in question are not possible to replicate in the current `UI::LoadFont` impl.
![image](https://user-images.githubusercontent.com/1046448/212823298-30ab0fc3-c29c-44d6-8f9f-2c27fe6871de.png)

Currently, we can specify a min and a max glyph (inclusive, I gather), but can't represent anything more complex. 

The easiest implementation I can think of is adding a function like: 
```angelscript
Font@ UI::LoadFont(const string&in filename, float size, array<uint16> &in glyphRanges, bool fallbackExtendedIcons = false, bool fallbackArial = false);
```

The array would work the same as in imgui, except that imgui needs a `0` as the final element.

(Note: I removed the default font size since glyphRanges probably shouldn't have a default, but the order of arguments could be changed, too.)

**Comment by codecat** [comment]
You can now pass an array of `uint32` to `LoadFont`:
```asc
UI::LoadFont("RobotoSlab.ttf", 16, { 0x20, 0xFF, 0x3C0, 0x3D0 });
```
Incidentally, I found some more issues with font range loading, so those have also been fixed!
