### ISSUE TITLE
plugin review comments leave no physical trace on the plugin dashboard

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#237]
just looks like this
![image](https://user-images.githubusercontent.com/1046448/213251140-b5ef849a-00d6-4a59-bd63-2bd7e429bb3f.png)
not very useful

**Comment by codecat** [comment]
I think there might be an existing issue for this 🤔

**Comment by XertroV** [comment]
I couldn't find anything with a quick search. mb we've just talked about it before? feels familiar like something I ran into in like first 1/2 of 2022
