### ISSUE TITLE
Assertion failure while trying some stuff with refs and startnew

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#241]
This was while developing MLHook

![image](https://user-images.githubusercontent.com/1046448/213579281-72dff896-96d2-4b3e-9046-1a60e266dea5.png)

This is the line I changed when reloading:

![image](https://user-images.githubusercontent.com/1046448/213579411-3fb2c60e-6e07-4d11-849d-46864872726c.png)

That is, passing `cast<ref>({cast<ref>(layer), cast<ref>({pageName})})`. 

I had a compile error before this, so MLHook wasn't loaded beforehand.

Follow up exceptions when pressing ignore: 
![image](https://user-images.githubusercontent.com/1046448/213579757-2276200b-787c-41ba-8300-1322787a466f.png)

No crash after that tho, so this is the compile error it threw back: 
![image](https://user-images.githubusercontent.com/1046448/213579897-1334d5f4-8840-498c-b643-a8e3f3b1d1bc.png)

**Comment by XertroV** [comment]
For curiosity's sake, this works tho: 
```angelscript
ref@[] ud;
ud.InsertLast(layer);
ud.InsertLast(array<string> = {pageName});
CtrlButton("Copy ML", OnClickCopyML, ud);
```
The `array<string> = ` is required.

**Comment by codecat** [comment]
You'll want to report this [here](https://www.gamedev.net/forums/forum/34-angelcode/).

**Comment by XertroV** [comment]
Done: https://www.gamedev.net/forums/topic/713693-assertion-failure-when-doing-funky-stuff-with-refs/

**Comment by codecat** [comment]
Seems to have been fixed as of January 26th, according to the linked thread 👍
