### ISSUE TITLE
reloading a class with a shared export does not allow the shared export to be changed

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#244]
e.g.:

mlfeed:
- PlayerCpInfo_V1

buffer time:
- imports and uses mlfeed and that class

Changing the class and reloading mlfeed will result in an error about shared classes having different definitions

**Comment by codecat** [comment]
I can't reproduce this. Here's my setup:

# A
## `info.toml`
```toml
[script]
dependencies = [ "B" ]
```

## `Main.as`
```asc
void Main() {
  print("A");
  auto f = Foo();
}
```

# B
## `info.toml`
```toml
[script]
shared_exports = [ "Export.as" ]
```

## `Export.as`
```asc
shared class Foo {
  Foo() {
    print("Foo()");
  }
}
```
## `Main.as`
```asc
void Main() {
  print("B");
  Foo();
}
```

And here's the output after editing `Export.as` (editing a function or adding another function I get the same result) and reloading `B`:
![image](https://user-images.githubusercontent.com/136534/213868894-38d4f4be-0c89-4dc8-a803-2486d18368c8.png)

However, if add another function to the `Foo` class and **only** reload `A`, I get the error, which would be expected in this case, because the definition is different in `B`, which has not reloaded:
![image](https://user-images.githubusercontent.com/136534/213868961-6a7f9df6-9280-4ecc-81f1-ffacbe5b1e97.png)

**Comment by codecat** [comment]
Here's a zip with both plugins `A` and `B`.
[AB.zip](https://github.com/openplanet-nl/issues/files/10472256/AB.zip)

**Comment by XertroV** [comment]
Thanks for the zip -- will look into this today. 

I'm wondering if mb I did something like update the mlfeed function, copy in new files to plugins/mlfeed (which often happens automatically on any file change), and then reload buffer time but not MLFeed or something.

In any case, will see if I can reproduce on my side and LYK anything I find.

**Comment by XertroV** [comment]
So, for reference, this is what I get changing a shared class: 
![image](https://user-images.githubusercontent.com/1046448/213975425-32d106f8-e059-4703-b93b-9fe0ee10241d.png)

Changing it back and reloading works as expected.

Reloading twice (after reloading the first time with a changed shared decl) does not fix.

**Comment by codecat** [comment]
There must be some shared copy of `HookKoStatsEventBase` still in memory somewhere. It could be the same exact shared class in a plugin that might not have a dependency, perhaps you have the script exist somewhere twice? Or maybe there some dependent not being unloaded correctly, do you see any potential missing plugin?

**Comment by XertroV** [comment]
There should be no other copy of it physically, like as source code (if there were, restarting the script engine shouldn't fix it, right, b/c of conflicting shared definitions).

I'm not sure `HookKoStatsEventBase` is alone in this case -- it's just the one that I changed to get the screenshot. It happens with the new classes I've added, too (which are only used by 1 other plugin atm; the dev version of buffer time).

The only thing that comes to mind is that there is a race condition involving MLHook's cleanup, maybe?

MLFeed has classes in this sort of inheritence structure (base class on left):

`shared MLHook::HookMLEventsByType` < `shared MLFeed::HookXXXEvents_V1` < `shared MLFeed::HookXXXEvents_V2` < `InternalSubClass`

MLHook accepts classes inheriting from `MLHook::HookMLEventsByType`. So maybe the MLFeed classes aren't being cleaned up by MLHook properly (or GC doesn't kick in early enough), and that's what's doing it?

MLHook should remove all references to those classes when the cleanup function is called though. Maybe I missed something.

I guess I could try changing an MLFeed class, reloading MLHook, and see if that fixes it. If it does, then it narrows things down a lot.

----

WRT other dependent plugins, I will try a minimal case with only mlfeed and buffer time.

**Comment by XertroV** [comment]
Okay, reloading MLHook allows for changes in shared classes.

**Comment by XertroV** [comment]
Yeah okay, looks like a bug with MLHook where it wouldn't clear hook classes properly. This patch fixes it and I can reload changes in MLFeed shared classes (even while a playground is loaded)

I think it was probably that the list returned by `GetHooksByPlugin` was not being cleared properly.

![image](https://user-images.githubusercontent.com/1046448/214446475-3bcda71a-ae33-4773-abfd-fe93cd531d1d.png)
