### ISSUE TITLE
Review queue length indicator?

### ISSUE THREAD

**Issue by sylae** [openplanet-nl/openplanet-issues#256]
Just thinking it'd be pretty poggers to have an indicator of how many plugins were waiting on review somewhere on the plugin admin page.

that way i can see oh hey there's deadass like 30 plugins waiting to be reviewed, maybe i'll hang on to this minor bugfix update until it slows down to avoid piling on

**Comment by codecat** [comment]
FWIW, "piling on" doesn't matter too much, and I definitely don't want to discourage people from submitting plugin versions. I think this could still be a good statistic but not sure how much it should be displayed, especially if people use it for that purpose 😅

**Comment by codecat** [comment]
Will close this for now, might reconsider later. It might help motivate me to do reviews quicker lol
