### ISSUE TITLE
Cache `UI::IsGameUIVisible()` result per frame

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#257]
So by my testing each call to `UI::IsGameUIVisible()` costs about 0.126 ms. 

I tested this by putting 10 calls to `UI::IsGameUIVisible()` in my render function.
Execution time went from 0.19ms avg to 1.45ms avg.

Considering this is a pretty common function to call, I guess that there is a significant impact on overall execution time. It might provide a decent performance boost to cache this value each frame internally.

**Comment by codecat** [comment]
Good call, I'll fix this.
