### ISSUE TITLE
Suspicion: Accessing ManialinkPageUtf8 'early' can cause a crash

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#258]
I've been investigating some crashes around accessing UI layers. This sometimes affects MLHook while developing (not in normal use AFAIK), particularly the UILayers browser started crashing my game recently (when it didn't before). 

Additionally, while developing a different plugin I got some crashes accessing layers. Out of superstition I'm avoiding the first 2 layers in app.Network.ClientManiaAppPlayground, but I've had crashes on other layers, too.

I've changed all the code in MLHook and this new plugin to use ManialinkPage instead (the `wstring`), and I haven't got any crashes since. (MLHook's UILayers browser also now skips layers with 0 length `ManialinkPage`s, too.)

I don't know for sure that ManialinkPageUtf8 is the culprit, but thought I'd mention.

**Comment by XertroV** [comment]
Oh, also, I think it's safe to access ManialinkPageUtf8 after you access ManialinkPage. That's also a suspicion, but it sorta makes sense.

**Comment by codecat** [comment]
It would be nice if you had a simple reproduce script. Just accessing ManialinkPageUtf8 doesn't seem to be enough in my case.

**Comment by XertroV** [comment]
I wrote a reproduction script -- it seems like it's not ManialinkPageUtf8, but the 2nd layer (that has no body). Note: this works for both ManialinkPage and ManialinkPageUtf8 (doesn't matter which is first)

```angelscript
void Main() {
    while (true) {
        auto app = cast<CTrackMania>(GetApp());
        while (app.Network.ClientManiaAppPlayground is null) yield();
        auto cmap = app.Network.ClientManiaAppPlayground;
        uint cmapLoadedAt = Time::Now;
        while (app.Network.ClientManiaAppPlayground !is null && cmapLoadedAt + 30000 > Time::Now) {
            testCrash(cmap);
            if (cmap.UILayers.Length > 20) break;
            yield();
        }
        while (app.Network.ClientManiaAppPlayground !is null) yield();
    }
}

bool shouldCrash = true;
uint startAt = shouldCrash ? 0 : 2;

void testCrash(CGameManiaAppPlayground@ cmap) {
    print("\n\nTrying to crash...\n\n");
    for (uint i = startAt; i < cmap.UILayers.Length; i++) {
        print("layer " + i);
        // this crashes for 2nd layer (i=1):
        print("first 100 chars: " + cmap.UILayers[i].ManialinkPageUtf8.SubStr(0, 100).Trim());
        // this also crashes:
        print("first 100 chars: " + string(cmap.UILayers[i].ManialinkPage.SubStr(0, 100)).Trim());
    }
    print("\n\ndone trying to crash this frame.\n\n");
}

```

```toml
[meta]
name = "crash test manialinkpageutf8"
author = "XertroV"
category = "Crash Tester"
version = "0.1.0"

[script]
```

**Comment by codecat** [comment]
Thanks! Turns out this was due to some faulty code that could happen when calling `Trim()` on an empty string.
