### ISSUE TITLE
Math::Angle not working correctly?

### ISSUE THREAD

**Issue by Atheuz** [openplanet-nl/openplanet-issues#259]
In the Math namespace (https://openplanet.dev/docs/api/Math), you have functions for getting the angle between vectors.

    float Math::Angle(const vec3&in a, const vec3&in b)
    float Math::Angle(const vec2&in a, const vec2&in b)

An example expected outcome of using this could be what Wolfram Alpha gives you with this query:
For vec3:

    Angle between (-124.851, 0.1475, -42.072), (-0.958411, -0.0140488, -0.285024) => 2.23633° or 0.0390313 radians

For vec2:

    Angle between (-124.851, -42.072), (-0.958411, -0.285024) => 2.0606° or 0.0359642 radians

If you run these in OpenPlanet:

    Math::Angle(vec3(-124.851, 0.1475, -42.072), vec3(-0.958411, -0.0140488, -0.285024)) => 0
    Math::Angle(vec2 (-124.851, -42.072), vec2(-0.958411, -0.285024)) => 0

Another example:

    Angle between (-124.851, 55.234), (45.2132, 30.241) => 122.359° or 2.13556 radians.

If you run that in OpenPlanet:

    Math::Angle(vec2(-124.851, 55.234), vec2(45.2132, 30.241)) => 3.14159

This does not seem like the intended behaviour of these functions.

**Comment by Atheuz** [comment]
Normalized vectors seem to work correctly though it seems:

     Math::Angle(vec2(-124.851, 55.234).Normalized(), vec2(45.2132, 30.241).Normalized()) => 2.13556

**Comment by codecat** [comment]
I think this is intended, as the maths library generally expects normalized vectors for these kinds of things, so I will close this issue.
