### ISSUE TITLE
loading the same (or learly the same) plugin from 2 different .op file will crash the game if you try and unload one

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#261]
loading the same (or learly the same) plugin from 2 different .op file will crash the game if you try and unload one -- as best as i can tell, at least.

example files:
[DID-twice-crash.zip](https://github.com/openplanet-nl/issues/files/10583345/DID-twice-crash.zip)

**Comment by codecat** [comment]
Is it only with DID, or can you make a minimal reproduction?

**Comment by XertroV** [comment]
[crash-on-load-example.zip](https://github.com/openplanet-nl/issues/files/10727182/crash-on-load-example.zip)

In trying to reproduce this I got a different crash (well maybe different). 

Replication:
1. put `crash-on-unload-helper-dev` in plugins directory
2. start game because I forgot to put the .op file in there
3. copy .op file in
4. load .op file
5. enjoy crash

I left the dependencies there but I don't think they're important. (maybe) Will try without and update if it fails.

**Comment by XertroV** [comment]
[crash-on-reload.zip](https://github.com/openplanet-nl/issues/files/10727201/crash-on-reload.zip)

Uhh okay, weirder crash (no deps in info toml):

1. copy in `crash-on-unload-helper-dev`
2. start game
3. copy .op file
4. reload  `crash-on-unload-helper-dev`
5. enjoy crash

this might be due to the module name?

**Comment by XertroV** [comment]
ofc, the crash helper plugin unloads fine if you only have 1 there.

**Comment by codecat** [comment]
This was indeed caused by them using the same module name. I have added a proper check for this now, plugins can no longer use the same module name.
