### ISSUE TITLE
Overlay toggle key setting should not display keys that aren't actually available

### ISSUE THREAD

**Issue by TufoXD** [openplanet-nl/openplanet-issues#262]

**Comment by codecat** [comment]
Xbox keys are not actually supported there unfortunately. I'll have to make sure those are unselectable.

To reset the key:

1. Close the game
2. Open `C:/Users/Username/OpenplanetNext/Settings.ini` in Notepad
3. Change `OverlayKey` to `114` (F3) or remove the entire line
4. Save the file
5. Start the game
