### ISSUE TITLE
Sqrt'ing a negative number appears to cause a crash

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#267]
Changing a `Math::Sqrt(value)` to `Math::Sqrt(Math::Abs(value))` prevented this crash, so I assume it's due to negative numbers.

Sorry about the low quality screenshot: 
![image](https://user-images.githubusercontent.com/1046448/217191057-0dabce9f-7e91-4aa5-94c8-343703666a63.png)

**Comment by codecat** [comment]
I think this is more likely due to a value of `Inf`, `-Inf`, or `NaN`. The assertion is in some GLM code, which means the value you're getting from `Sqrt()` is being passed to (what looks like) some matrix calculations, causing the assertion.
