### ISSUE TITLE
Docs: add example of array.sort() usage

### ISSUE THREAD

**Issue by sylae** [openplanet-nl/openplanet-issues#272]
Using the anon function/closure/callback/whatever the fuck it's called for the .Sort function is pretty useful, but for someone who hasn't dealt with angelscript funcdef's and whatnot before its a fukken nightmare.

Given how generally useful sorting is, it might be worthwhile to add an example of this to the docs? Something like this idk...

```angelscript
funcdef bool LessSort(const Foo@ &in a, const Foo@ &in b);
bool LessSortFunc(const Foo@ &in a, const Foo@ &in b) {
    return a.bar > b.bar;
}

// ...

FooArray.Sort(LessSort(LessSortFunc));
```

**Comment by XertroV** [comment]
related: https://github.com/openplanet-nl/issues/issues/126
