### ISSUE TITLE
Math::Floor and friends, but that take float and return int?

### ISSUE THREAD

**Issue by sylae** [openplanet-nl/openplanet-issues#274]
![image](https://user-images.githubusercontent.com/2791628/219812777-5f26c0de-12ab-4014-93dd-52c3667044a3.png)

**Comment by sylae** [comment]
oh i guess angelscript doesn't support 2 functions with same args but diff return types :pensive:

**Comment by codecat** [comment]
There's two reasons why it doesn't return integral types:

1. It fits better with other mathematical functions when chained with other operations
2. [The types are not as compatible as you might think](https://stackoverflow.com/questions/15348180/why-doesnt-floor-return-an-integer)
