### ISSUE TITLE
Log unloading and toggling of plugins

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/openplanet-issues#275]
I think it would be helpful to log when a plugin has been toggled on/off as well as when a plugin is unloaded (just for more traceability for devs)

More often than not I sometimes accidentally toggle a plugin instead of reloading it. I guess I just like the idea that you can see exactly which events happened

**Comment by codecat** [comment]
Additionally, we should display the current toggle state in the log of loaded plugins, too.
