### ISSUE TITLE
nvg fonts sometimes don't load fallback icons

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#276]
it seems like sometimes nvg fonts don't load icons properly. Text seems to be fine.

This seems separate to https://github.com/openplanet-nl/issues/issues/232 -- it has been an issue during map info development (possibly solved by the fix in #232 -- not sure), and bmx22c posted something about the icons not showing up in Show Editor Inputs. (The keys are all text, and mouse is icons, so I'd expect keys to work but mouse indicators not to work in this case.)

link to bmx22c's report: https://discord.com/channels/276076890714800129/276076890714800129/1076959972220473416

A difference between the two cases, tho, is that the icons were rendered as a tall rectangle in the map info case (particularly the `::Users` icon shown above the leaderboards UI element), and in the show editor inputs case the icon doesn't appear at all. Not sure if that's because there's other text in the map info case but not in the editor inputs case.

Reloading usually fixes it.

Although I didn't notice it ever happening without reloading the plugin, it's possible that it can happen from a fresh game start. I asked bmx22c about that here: https://discord.com/channels/276076890714800129/1069966744459943968/1077124034682159195 
Update: yeah it didn't involve any reloading of plugins, so seems likely that it was like that from the time the game was loaded.

**Comment by codecat** [comment]
Yeah, #232 wasn't a great fix, it indeed introduced a different bug. I have a note in the code to fix it.
