### ISSUE TITLE
STRETCHED TEXTURES on TM2020

### ISSUE THREAD

**Issue by ErwideK** [openplanet-nl/openplanet-issues#279]
OK, I play trackmania 2020 for a long time already, and I installed an update of OpenPlanet because there was one available. I didn't make the connection with the textures suddenly becoming stretched and all bugged. And today I installed TM2020 on Steam, and I saw that my textures were completely fine. Then I installed OpenPlanet (the latest version of course) and it was all bugged again. I made the conclusion that OpenPlanet actually bugs the textures.

There is a post on the Trackmania Forum, that deals with this bug. Apparently, most people impacted by this bug are people with AMD graphics.

[https://discussions.ubisoft.com/topic/181652/textures-oversized-after-the-december-update-post-here?lang=en-US&page=1]

I searched a bit in the settings if there was something to change, but I didn't find anything ... I also don't really understand so I prefer not touching or modifying anything ...

**Comment by codecat** [comment]
This is very likely **not** a problem in Openplanet, but in AMD's drivers. Openplanet doesn't touch any of the rendering like that and it might just be a side-effect of the bug. In that same thread, you can see people mention that even when disabling Openplanet they still have the issue.

Will close for now until there's more of an indaction that this is truly related to Openplanet.
