### ISSUE TITLE
loading a plugin from the UI which includes a globally instantiated font throws an exception

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#280]
when you load a plugin via the dev menu that has a custom font, you can get an error about loading fonts within the render loop.

conditions for this are basically:
1. have a globally instantiated font; e.g., a global statement like `UI::Font@ g_font = UI::LoadFont("DroidSans.ttf", 12.7);`
2. trigger the loading of that plugin via something in the Render loop, like developer > load plugin.

my guess is that this happens b/c the load plugin call is not done in a coroutine.

can provide more details if necessary.

**Comment by XertroV** [comment]
Note that this is triggered by `developer > reload` but not via `ctrl + r`

**Comment by codecat** [comment]
Generally I've always recommended people to load fonts inside of `Main()`, but maybe I should properly fix this.

**Comment by XertroV** [comment]
> Generally I've always recommended people to load fonts inside of `Main()`, but maybe I should properly fix this.

This can cause timeouts for the plugin when loading a font takes more than 1000ms. Instantiating it globally outside of a function avoids this.

**Comment by codecat** [comment]
Oh, that also sounds like a bug to be honest, and really shouldn't be the behavior we're looking for.

Fonts are a difficult topic due to ImGui's nature so will have to think a bit about this.

**Comment by codecat** [comment]
This issue is no longer valid since we've changed how global variables are initialized, they are now also subject to script timeouts.
