### ISSUE TITLE
Since i downloaded openplanet i can only move backwards in the map builder/editor

### ISSUE THREAD

**Issue by kackys** [openplanet-nl/openplanet-issues#300]
So when i wanna make a new map(im a mapper) and i hold alt to move my camera and stuf i can only use my down arrow to go backwards but the other three just dont work. Has anyone experienced this problem or still has this and does anyone know how to fix this?

**Comment by codecat** [comment]
Hmm not entirely sure what you mean, but try disabling this option in the Openplanet settings and let me know if you still have this problem:

![image](https://user-images.githubusercontent.com/136534/233798623-7bf6b0bb-592b-4e38-ab39-c242421c759b.png)

**Comment by kackys** [comment]
sorry for reacting so late but you are fast. i am looking right now. will keep ya posted

**Comment by kackys** [comment]
i actually can't believe it. 1 setting that caused me to think my game got coruppted or shiz

**Comment by kackys** [comment]
hey just got a new pc and it did it again. i used your post and it still be buggin me man. So much love for your help. stiil
