### ISSUE TITLE
Make 'not in developer mode' error more obvious

### ISSUE THREAD

**Issue by ArEyeses79** [openplanet-nl/openplanet-issues#305]
I recently shared a plugin with someone and it took a few minutes to realise this was why it wouldn't work for them. It didn't seem to have a popup similar to compilation fails (unless we both missed it), and the message in log just said info.toml was invalid. (rather than saying that developer mode is needed for unsigned files)

**Comment by codecat** [comment]
![image](https://user-images.githubusercontent.com/136534/235361709-0223ceb8-22a5-4006-84e6-1b6c6443b907.png)
