### ISSUE TITLE
Weird values from UI::SliderFloat2

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#306]
I have a very weird bug with some imgui inputs. This sometimes doesn't cause an issue, like the first attached clip. Someitmes it does, like the second. 

It appears that the value being returned from the UI method isn't constant even tho I'm not touching it. (examples below)

I really don't get what could be causing this. Like some openplanet bug? maybe bad ram on my part? idk.

This happens with both openplanet versions: .36 and .39.

I have also had crashes that might be associated with re-entering mediatracker or changing the label of the wacky input from `Edge Padding (x,y pct)` to `Edge Padding (x,y pct)##asdf` and something like `Edge Padding (x,y pct)###edge-padding-pct`. 

the relevant code is the following:

```angelscript
        auto inPadding = MathX::Clamp(m_padding, -50., 100.);
        m_padding = UI::SliderFloat2("Edge Padding (x,y pct)", inPadding, -50., 100., "%.1f");
        // m_padding = MathX::Clamp(m_padding, -50.0, 100.0);
        if (!Vec2Eq(m_padding, inPadding)) {
            trace('mismatching in/out padding: ' + m_padding.ToString() + ' vs. orig: ' + inPadding.ToString());
        } else {
            trace('matching in/out padding: ' + m_padding.ToString() + ' vs. orig: ' + inPadding.ToString());
        }
```

the MathX::Clamp is just a wrapper of type `vec2 Clamp(vec2 val, float min, float max)`.

---

examples:

This causes some odd effects in the minimap wizard:

https://user-images.githubusercontent.com/1046448/235654652-c6ce10ac-da9b-4d65-8ed0-bed4c03d0855.mp4

https://user-images.githubusercontent.com/1046448/235655014-b2d8e50f-a0df-4042-9db4-818a61e18708.mp4

![image](https://user-images.githubusercontent.com/1046448/235649061-ad211878-91a2-414a-976f-d7b7100f7a26.png)

It doesn't appear to always oscillate between extremes: 

![image](https://user-images.githubusercontent.com/1046448/235655303-2a3d4728-cbd8-435c-876d-52f539706fa6.png)

samples of copy-pasted values:
- -938618931642368.0
- 8935756768739328.0

**Comment by XertroV** [comment]
I can't replicate this after updating windows + rebooting.

**Comment by codecat** [comment]
2 questions:

* Are you sure the implementation of `MathX::Clamp` is solid and isn't causing this?
* Are you sure there isn't a difference between edge & live? I did make a change to `UI::SliderFloat2`, but I didn't think it would cause any problems like this.

**Comment by XertroV** [comment]
> Are you sure the implementation of MathX::Clamp is solid and isn't causing this?

I think it's fine, but also, MathX::Clamp is applied before inPadding is set, and the values compared are between inPadding and the return value of UI::SliderFloat2.

```angelscript
namespace MathX {
    vec2 Clamp(vec2 &in val, float min, float max) {
        return vec2(
            Math::Clamp(val.x, min, max),
            Math::Clamp(val.y, min, max)
        );
    }
}
```

> Are you sure there isn't a difference between edge & live? I did make a change to UI::SliderFloat2, but I didn't think it would cause any problems like this.

I installed .36, started TM and got an update prompt (for edge). I then replicated the issue. So I'm fairly sure it happened with both.

**Comment by XertroV** [comment]
Also, `MathX::Clamp` is something I added in trying to diagnose this issue. I don't have a clamp in the current version (both live and in-review)

**Comment by XertroV** [comment]
So, some important things:

- I tried changing the variable name, whether it was a setting or not, and the label of the `UI::SliderFloat2` and none of those helped. 
- The problem also existed for `UI::InputFloat2`
- The problem does not appear to exist for 2x `UI::SliderFloat`s

Here's a video demo of it *only* happening when the SliderFloat2 is rendered.

https://user-images.githubusercontent.com/1046448/236387137-c2ed0013-6992-49d4-b99b-ef6afa66ed5d.mp4

**Comment by XertroV** [comment]
Oh, also SBVille also had this problem in exactly the same way.

**Comment by codecat** [comment]
Note that I fixed this, but with a little weird workaround. I'll have to get back to this at some point and figure out what exactly went wrong.
