### ISSUE TITLE
Add an explict 'save settings' button in settings (mb under general)

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#307]
Sometimes, when testing things that might crash the game, I want to explicitly save settings to avoid doing a full, clean restart. Basically to avoid windows showing up on load or to keep the 'most recent' plugin to reload, etc.

ATM I just add `Meta::SaveSettings();` as a line to the start of a plugin.

**Comment by codecat** [comment]
Closing the settings dialog also saves it, if that makes it easier. Adding a button for this might be a little bit confusing? 🤔 Unless there's some "Advanced mode" that shows something like this. But I'm not sure I **really** see the benefit of this.

**Comment by XertroV** [comment]
If closing the settings is equivalent, that's fine. I had a suspicion that it wasn't in the past (like the set of stuff that got saved is slightly different), but that's probs a mistake on my end. Will reopen if closing the settings window isn't sufficient for whatever reason.

**Comment by codecat** [comment]
Yep, you should see "Saving settings" in the log as well when you close the dialog. 👍
