### ISSUE TITLE
`Net::HttpRequest::ResponseCode` blocks

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#317]
If you call `req.ResponseCode()` before the request is done, it appears to block. It would be nice if it returned -1 or something instead so it could be safely called from UI code.

**Comment by codecat** [comment]
I will make it so this will throw an exception instead (along with String) so calling Finished will be required. I don't know if there will be any need for it, but maybe I should add a WaitSync method too or something.
