### ISSUE TITLE
base64 encode decode strings

### ISSUE THREAD

**Issue by sylae** [openplanet-nl/openplanet-issues#331]
The ability to take a base64 string and get its binary equiv and vice versa

🥺

**Comment by skybaks** [comment]
I think this is already available as member functions of `MemoryBuffer`

https://openplanet.dev/docs/api/global/MemoryBuffer/WriteFromBase64

https://openplanet.dev/docs/api/global/MemoryBuffer/ReadToBase64

**Comment by chipsTM** [comment]
Yes, it is possible with the current functions, but it's a bit messy :)

https://github.com/chipsTM/tm-websockets/blob/798ec9fda54428d896a2bbe1add93ed2c1eeadc4/src/Common.as#L9-L36
