### ISSUE TITLE
Move last openplanet.log instead of overwriting.

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#333]
Sometimes i restart TM too early before I backed up the old log; having access to the log from the previous run would be useful (can be overwritten after that)

**Comment by codecat** [comment]
Has the potential to create spammy amounts of logfiles (and confusion among users when we ask them for log files), so if we add this, it should be behind a setting and disabled by default.

**Comment by XertroV** [comment]
> Has the potential to create spammy amounts of logfiles 

I was thinking of just having 1 file, like `PriorOpenplanet.log.bak` or something. On startup, if Openplanet.log exists, it gets moved to that file.

No worries re putting it behind a setting.

**Comment by codecat** [comment]
Explicitly renaming it could be an option indeed; `OpenplanetOld.log` or something would avoid confusion. 👍

**Comment by skybaks** [comment]
+1 to this idea. Just one log file from the prior run would be enough for me as well because it would be nice to scan through it while relaunching the game following a crash
