### ISSUE TITLE
Stats plugin null pointer access

### ISSUE THREAD

**Issue by bmx22c** [openplanet-nl/openplanet-issues#337]
Hello!
The Stats plugin seems to have a null pointer access error. Idk if it triggered because I was on a Shootmania map (CharacterPilot in TM2020) or not.
Screenshot below:
![image](https://github.com/openplanet-nl/issues/assets/6803869/a3aca204-56c5-4d86-8e82-f4a42ad71cdc)

Thanks!

**Comment by codecat** [comment]
This implies that `GetApp().Network` can be null, which should never be possible. I think you previously mentioned this causes a crash too? Perhaps something else sketchy is going on here?

**Comment by codecat** [comment]
Closing because I'm not sure this is still a problem. Feel free to let me know if you encounter this again tho!
