### ISSUE TITLE
Skid marks issue

### ISSUE THREAD

**Issue by DjnxxD** [openplanet-nl/openplanet-issues#340]
im having a problem on the plugin called skid marks manager, when i use custom skids, the skids become totally black and thick, i cant use that plugin.
pls help me to resolve the issue :D

**Comment by davidbmaier** [comment]
Since this isn't a problem with Openplanet itself, please report it to the plugin creator instead (there's a similar issue that was recently opened, might be the same problem): https://github.com/GreepTheSheep/openplanet-skidmarks-manager/issues

**Comment by codecat** [comment]
Linking the issue directly: https://github.com/GreepTheSheep/openplanet-skidmarks-manager/issues/8
