### ISSUE TITLE
Missing IO::Copy()

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/openplanet-issues#341]
I don't see a method in the [IO namespace](https://openplanet.dev/docs/api/IO) for copying files. I guess I could use IO:File to read in a file and then write it out to my target location but I would prefer not to do that if it is not hard for you to add a Copy method.

**Comment by XertroV** [comment]
>  I guess I could use IO:File to read in a file and then write it out to my target location

FWIW that's what I do

**Comment by skybaks** [comment]
Fwiw i did end up working around this with xertrovs suggestion. If this method is added i would be happy to switch my code over to it tho
