### ISSUE TITLE
Auto scroll to bottom of logs when opening/switching tabs

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/openplanet-issues#342]
Often times when I have logs tabbed/docked to window or reopening the logs, I have to rescroll through _everything_ just to get back to the bottom.

Can it be the behavior by default to auto jump to bottom of logs?

**Comment by codecat** [comment]
Does this only happen when the window is docked?

**Comment by chipsTM** [comment]
Appears to be the case. Easiest way I can repro is when reloading a plugin while log is docked and another tab is open. So when I switch back to it, it shows the top.

However if you have a script that prints to log, it appears to scroll automatically down to bottom (after regaining focus)
