### ISSUE TITLE
AFK Queue Tool crashing my game when trying to save a map in the editor 

### ISSUE THREAD

**Issue by LimoneHD** [openplanet-nl/openplanet-issues#343]
everytime i tried to save a map my game crashes and when i deinstalled afk queue tool it started working normaly again 
i sadly didnt get any crashreports so i can not provide anything helpfull besides the info kind regards Limone

**Comment by sylae** [comment]
Hi there,

This tracker is just for issues relating to the openplanet engine itself, you'll want to get in touch with the plugin developer. I'll @ them on discord but most likely they'll need more information to resolve this :)
