### ISSUE TITLE
Json GetType() on missing key is 0

### ISSUE THREAD

**Issue by ArEyeses79** [openplanet-nl/openplanet-issues#345]
`jsonvalue['missing_key'].GetType()` will be `0`, rather than a known Json type such as Null (`Json::Type::Null, 6`)

**Comment by codecat** [comment]
Is this still an issue on the latest version?

**Comment by ArEyeses79** [comment]
Yes (in version 1.25.45)

**Comment by codecat** [comment]
I fixed this by adding `Json::Type::Unknown`.
