### ISSUE TITLE
Dosent show when i rank up in prestige

### ISSUE THREAD

**Issue by HyggeBis** [openplanet-nl/openplanet-issues#347]
I dont think its a bug, but actually a setting.
When i for example rank up to gold etc in ranked, the new prestige thingy dosent pop up.
It just displays a little grey window top left (i think its a openplanet plugin). 

How do i turn it off, so i see the normal nadeo thing?
Maybe it's an existing feature in a plugin i already have?

Thank you!

**Comment by sylae** [comment]
Do you have the afk queue plugin installed? Iirc for horrifying nadeo reasons the prestige skin alert is handled via the same mechanism as matchmaking stuff.

**Comment by HyggeBis** [comment]
@sylae yeah i have the afk que tool, but i dont see any setting to disable it.
Also i saw other streamers with the afk que tool, where its not happening

**Comment by codecat** [comment]
Closing this because I'm not sure it's an Openplanet-specific issue.
