### ISSUE TITLE
Possible to change default imgui input width?

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#349]
It'd be nice to have the default imgui input width take like 50% of the available space instead of more like 75% or whatever it does. 

Is this something that's possible to change? I had a brief look at imgui and couldn't even tell where that default would be.

**Comment by skybaks** [comment]
Is this for text input or numbers? In both cases i think i agree with this request. I often find that my number inputs have the +/- buttons clipping off the window because the box is so big.

**Comment by codecat** [comment]
What about [`PushItemWidth`](https://openplanet.dev/docs/api/UI/PushItemWidth) and [`PopItemWidth`](https://openplanet.dev/docs/api/UI/PopItemWidth)?

**Comment by XertroV** [comment]
I will check! That looks like a good bet.
