### ISSUE TITLE
Expose plugin execution limits

### ISSUE THREAD

**Issue by sylae** [openplanet-nl/openplanet-issues#350]
Would be handy for bulky but yieldable loops if we could see what the hard script limit is, as well as the "laggy plugin" warning limit.

that way you can just check how much time you have left, and if you're cutting it close, yield until next frame. beats having to yield every frame esp if an individual operation is fast but you have a billion of them, yknow?

**Comment by codecat** [comment]
I am not sure this should be something that a plug-in can control or see; plug-ins should by default already be performant. Trying to work around these warnings any other way feels like "cheating" in a way.

**Comment by codecat** [comment]
I will close this for now because I'm not entirely sure this needs to be implemented right now. If anyone feels like this would benefit stuff, please feel free to reply with an example use-case 😄
