### ISSUE TITLE
unclear what the preprocessor DEPENDENCY_ defines is for a plugin whose ID contains dashes

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#355]
I've tried multiple times in different ways to check a preprocessor statement like the following, where a dev plugin specifically has dashes in the directory name (and thus the ID):
```angelscript
#if DEPENDENCY_BETTER-ROOM-MANAGER-DEV
// ...
#endif
```
The docs aren't very helpful here, they only mention:

> If an optional dependency is installed however, it will add a preprocessor definition that you can use in your scripts. The definition will have a prefix of `DEPENDENCY_` followed by the plugin ID in uppercase, with spaces replaced by underscores.

It'd be nice if the docs were improved to account for this -- alternatively, this might be a bug.

I have tried various things which don't work:
- replacing dashes with underscores
- omitting dashes
- lowercase plugin IDs (which match normal ones)

Also, https://openplanet.dev/docs/tutorials/plugin-dependencies is not accessible via https://openplanet.dev/docs/tutorials/ and IDK how to find it via the site (I found it via searching).

**Comment by codecat** [comment]
This is happening beause [ccpp](https://github.com/codecat/ccpp) doesn't support dashes for identifiers (words):

https://github.com/codecat/ccpp/blob/bf9bd0b8dfe83444a5bff5d0ecf7ad8e34602fc7/ccpp.h#L203

I will fix this by replacing `-` with `_` as well.

**Comment by codecat** [comment]
Additionally, I've added `.` as a character that gets replaced by an `_` as well, and I've already updated the documentation to reflect this. I've also added a link from the tutorials page. The page was already linked on the [info.toml reference](https://openplanet.dev/docs/reference/info-toml).

**Comment by XertroV** [comment]
Sounds perfect, thanks!
