### ISSUE TITLE
Lots of "Script with the same name was already added (this was a but, please report!)" when adding MLHook to `export_dependencies` of MLFeed

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#357]
If I add MLHook to `export_dependencies` of MLFeed, I get lots of "Script with the same name was already added (this was a but, please report!)" errors. (That said, things seem to load)

Although all plugins using MLFeed already import MLHook, it'd be nice if they didn't have to, so I was experimenting with `export_dependencies` to see if the dependency experience could be improved (for devs).

![image](https://github.com/openplanet-nl/issues/assets/1046448/e290e9ac-b711-4707-b72a-2f1a484b899c)

**Comment by codecat** [comment]
This will now give a nicer warning on build:

![image](https://github.com/openplanet-nl/issues/assets/136534/276d5f6a-8491-4d9b-8313-772bdee64e84)
