### ISSUE TITLE
MemoryBuffer doesn't initialize memory

### ISSUE THREAD

**Issue by crow-fisher** [openplanet-nl/openplanet-issues#358]
Not sure if this is intended behavior or not - seeking on a MemoryBuffer to 0 allows you to see various JSON output of the game (mostly advertiser tracking mumbo jumbo). 

The behavior I expected would be to have the buffer itself have Beginning and End values, and either localize Seek to within the buffer itself (i.e., 128 is the 128th byte of the buffer) or just throw an exception if it's not within its bounds rather than arbitrarily trawling the game's memory space.

I'm assuming this is viewable without going through a socket to Python, but this is how I noticed the issue.

The 10k bytes in the code is arbitrary; I didn't play around with this to see how much I could pull out.

(Cropped) Image of example output: 

![image](https://github.com/openplanet-nl/issues/assets/46819631/86069a57-afca-41b4-ab54-7928e8717bac)

Code to reproduce: 

```angelscript
Net::Socket socket;

void Main() {
	socket.Connect("127.0.0.1", 13823);
}

void Render() {
	CSceneVehicleVisState@ visState = VehicleState::ViewingPlayerState();
	if (visState is null) {
		return;
	}
	MemoryBuffer buff(100000);
	buff.Seek(0);
	socket.Write(buff, 100000);
}

``` 
Python server:
```python
import socket
import numpy as np
# Define the server's host and port
HOST = '127.0.0.1'  # Loopback address for localhost
PORT = 13823       # Port to listen on

# Create a socket object
output_filename = "output.txt"

with open(output_filename, 'w+', encoding='utf-8') as output_file:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind((HOST, PORT))
        s.listen()
        conn, addr = s.accept()
        with conn:
            print(f"Connected by {addr}")
            while True:
                data = conn.recv(100000)
                if not data:
                    break
                utf8_string = data.decode('utf-8', errors='replace')
                output_file.write(utf8_string)
```

**Comment by codecat** [comment]
This is the expected behavior, there is no "out of bounds" here. You're just reading from uninitialized memory.

I can add an option to initialize such memory to 0, but it does add extra overhead.

**Comment by codecat** [comment]
Turns out this was already implemented! The second parameter in the MemoryBuffer constructor specifies the byte to fill the new buffer with.
```
IO::MemoryBuffer buffer(100000, 0);
```
