### ISSUE TITLE
Assertion failed and CTD leaving mediatracker (back to map error)

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#362]
![image](https://github.com/openplanet-nl/issues/assets/1046448/3ebe968b-f9a9-4c75-99a3-2513a1a9a903)

I'm not sure why this happened or if it's an angelscript thing (tho looks like it?)
I was dicking around in cheat engine, too, so not sure if I broke something.

**Comment by codecat** [comment]
Yes, this is from Angelscript. Is it reproducable w/o messing around with the process memory?

**Comment by XertroV** [comment]
I don't know, first and only time it's happened, and I don't know the plugin module (if any) in which the assertion failed. (Not sure if that would be possible to add to the log, it might help in future)

**Comment by codecat** [comment]
The assertion failure implies that a reference count is greater than 1 million (while it's trying to increase the reference). So if you were changing that refcount's memory, that would definitely happen.

Another case this might happen is if the memory was freed, but the refcount is still attempting to increase on that same memory.

**Comment by XertroV** [comment]
Ahh yep probably me then. I was trying to find a flag or something to disable moving object animations (they are paused in mediatracker). this would help a lot with placing moving items in the editor. As part of that I was searching for values like 0 and 1 that changed based on MT open/closed status. I probably set a bunch of values to different values trying to find if anything rowked, and one of those was probably a refcount thing. 

e.g., maybe i set it to 0 and then something subtracted 1 so it was 4 billion and then bang assertion failed.
