### ISSUE TITLE
Offzone patch outdated

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#377]
The "offzone" button still exists in the editor, but it doesn't work and the log says patch not found. I made a map with the feature sometime early this year or last year, so it has broken since then with some game update.
<img width="221" alt="Screenshot 2023-09-26 194452" src="https://github.com/openplanet-nl/issues/assets/37951898/48ba7265-5bf2-47d6-b1fe-98d3927ea4f3">
<img width="338" alt="Screenshot 2023-09-27 125913" src="https://github.com/openplanet-nl/issues/assets/37951898/4d7c2b50-4d51-4333-97fe-1a95f5d7611b">

**Comment by XertroV** [comment]
for devs, you can re-enable this by editing the Openplanet/Scripts/Plugin_editorDeveloper.as file. 

On line 188, in the `#if TMNEXT && !LOGS` branch, change this line
```
		"0F 84 ?? ?? ?? ?? 4C 8D 45 F0 BA 13",
```
to 
```
		"0F 84 ?? ?? ?? ?? 4C 8D 45 ?? BA 13 00 00 00",
```
Then save the file and reload this plugin
![image](https://github.com/openplanet-nl/issues/assets/1046448/9df1a2bd-52c9-415c-8a46-b99f1b1e4d7e)

**Comment by codecat** [comment]
Note that the pattern has changed at some point or another to `0F 84 ?? ?? ?? ?? 4C 8D 45 00 BA 13`, (`F0` -> `00`) which fixes this problem.

Will close for now as we have a new repository, please open an issue there if it breaks again: https://github.com/openplanet-nl/editordeveloper
