### ISSUE TITLE
Reproduction of Crash: Assertion Failed (Expression: value < 1000000)

### ISSUE THREAD

**Issue by crow-fisher** [openplanet-nl/openplanet-issues#379]
I've found a replication for the 'Assertion Failed' issue. This issue tends to come up infrequently when large amounts of objects are being created. 

Run "Do coroutine count testing" in the plugin - with 500k runnables (the default in the plugin), it only took running it twice to get the crash. Also, had an interesting case where the crash happened when I restarted the script engine (rather than hitting the plugin again itself). This seems to happen more quickly if it's run through coroutines rather than directly.

Repo: https://github.com/smalljustin/testing-yield

(the same is attached)

[testing-yield.zip](https://github.com/openplanet-nl/issues/files/12766122/testing-yield.zip)

Between this and the last replication attempt, the data arrays are within an object rather than being at the global level. 

(This same issue does come up inside a real use case in the COTD qualification grapher, albeit pretty rarely. So not purely theoretical!)

![image](https://github.com/openplanet-nl/issues/assets/46819631/b26ccfe1-4378-4e4d-9e42-dedffd7bf517)

**Comment by codecat** [comment]
I'll close this for now as it seems to be not a very practical issue, as you have noted. For reference, `asCAtomic` has these assertions as a safety mechanism, so this is not necessarily a bug either.

https://github.com/codecat/angelscript-mirror/blob/35623df4afc593dbdee9b5c60734c72d4842784f/sdk/angelscript/source/as_atomic.cpp#L46-L53

**Comment by infinisil** [comment]
Wirtual just hit this when he finished [Deep Slip](https://trackmania.exchange/mapshow/253616) after almost 4 hours: https://www.youtube.com/live/k-l5ixSuzlk?t=41080s

He's been given advice to hit ignore, hope that works out in the end! Edit: It did work out :)
