### ISSUE TITLE
compiler assertion failure line 14225

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#385]
![image](https://github.com/openplanet-nl/issues/assets/1046448/8d9bae6e-f3d7-4ce4-b5c5-0a5d5b81bdcd)

The problem in question was fixed with parens, I was doing
```angelscript
while (!UI::IsMouseDown() && (@editor = cast<CGameCtnEditorFree>(GetApp().Editor) !is null)) {
  //...
}
```
instead of 
```angelscript
while (!UI::IsMouseDown() && ((@editor = cast<CGameCtnEditorFree>(GetApp().Editor)) !is null)) {
  //...
}
```

**Comment by codecat** [comment]
Can you report this issue [here](https://www.gamedev.net/forums/forum/34-angelcode/)? A good reproduce-case would be to trigger the assertion without the Openplanet API.

**Comment by XertroV** [comment]
cool posted. also found this triggers it:
```angelscript
    string[]@ arr;
    while (false && (@arr = cast<array<string>>(null) !is null)) {
        break;
    }
```
