### ISSUE TITLE
Bug with OpenPlanet Plugins

### ISSUE THREAD

**Issue by Psymon69** [openplanet-nl/openplanet-issues#387]
OpenPlanet shows my plugins as installed but I can't acces any plugin except for Bingo for some reason
I reinstalled every plugin and restartet the game several times

Greetz Psymon 
(☞ﾟヮﾟ)☞

**Comment by codecat** [comment]
Can you post your `Openplanet.log` file, located in `C:\Users\Username\OpenplanetNext\Openplanet.log`?

**Comment by codecat** [comment]
Closing as this is now 2 weeks old.
