### ISSUE TITLE
ManiaExchange Random Map challenge not working.

### ISSUE THREAD

**Issue by PurplBlowfish** [openplanet-nl/openplanet-issues#389]
Sometimes it does work, but more often than not I hit "start random map challenge" and then the script shows me this.

![image](https://github.com/openplanet-nl/issues/assets/148804287/6329fc56-017b-4d0b-803b-2de82bdfc968)

**Comment by davidbmaier** [comment]
This issue tracker is for Openplanet itself (not for community-made plugins), you should report plugin problems in the plugin's repository directly: https://github.com/GreepTheSheep/openplanet-MXRandom/issues
