### ISSUE TITLE
bug in the map validator plugin

### ISSUE THREAD

**Issue by kawemm** [openplanet-nl/openplanet-issues#390]
Hello,

I made a time of 01:17.298 on my map, when i try to validate it with the plugin, it enters 01:57.298
gl fixing it and ty for what u do

kom

**Comment by XertroV** [comment]
This isn't the right place for this issue (you can discuss it on the openplanet discord server), but you are probably entering 117298 which is 117 seconds. If you want a time of 1:17, you need to enter 77298.
