### ISSUE TITLE
Assertion failed: '"pTexture != nullptr"'

### ISSUE THREAD

**Issue by AvondaleZPR** [openplanet-nl/openplanet-issues#393]
gwnMarty got this error and crash when loading my plugin. not sure what to make of it, ive never encountered it myself and loading older plugin version doesnt change a thing.
roguemania plugin. op version 1.26.5

Logs on different plugin version and with plugins enabled/disabled:
[Openplanet.log](https://github.com/openplanet-nl/issues/files/13245247/Openplanet.log)
[Openplanet-Old.log](https://github.com/openplanet-nl/issues/files/13245250/Openplanet-Old.log)
[Openplanet(1).log](https://github.com/openplanet-nl/issues/files/13245251/Openplanet.1.log)
[Openplanet(2).log](https://github.com/openplanet-nl/issues/files/13245252/Openplanet.2.log)

the file where texture loading happens:
https://github.com/AvondaleZPR/TM2020-RogueManiaGame/blob/main/ui.as
textures defined on lines 23-31. textures loaded on lines 50-60

**Comment by codecat** [comment]
This is likely because there's not enough video memory to store your loaded font in the font texture.
