### ISSUE TITLE
Standardize Compiler Messages to Enable Full Parsing

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/openplanet-issues#399]
As part of the Remote Build plugin and associated vscode plugin, the Openplanet.log gets read in to display compiler errors, warnings, and messages. VScode tasks support a problem matcher which is a regular expression that is applied to the output of a task to scan for things to highlight as problems.

This is the problem matcher which is currently being used in my VScode plugin:
```json
"pattern":[
    {
        "regexp": "^(.*) \\((\\d+), (\\d+)\\) :\\s+(WARN|ERR) : (.*)$",
        "file": 1,
        "line": 2,
        "column": 3,
        "severity": 4,
        "message": 5
    }
]
```
This matcher has no problem handling what I believe are output messages from the Angelscript compiler. However, there are some additional warnings which I believe that you implemented custom that do not follow this pattern. One example of this is the warning about `string` as a function argument instead of `string&in`.
It would be nice if those additional warnings and errors also followed this or another predictable pattern so that they could be parsed.

**Comment by codecat** [comment]
Sanity check errors will now look like regular script engine errors:

![image](https://github.com/openplanet-nl/issues/assets/136534/7bce9ea7-79f2-4f6a-a56b-5905de198fd0)
