### ISSUE TITLE
Missing functions in CSmArenaRulesMode (and mb elsewhere)

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#401]
If you search OpenplanetNext.json for `Activate or Deactivate SlowMotion on the player's vehicle with a 250ms delay` you'll find a doc entry that corresponds to `SetPlayer_Delayed_SlowMotion` which you can see in the ML docs here: https://bigbang1112.github.io/maniascript-reference/trackmania/class_c_sm_mode.html#ab9c69870ae4da083a20bb3818836df5d

It'd be nice if these were callable via the openplanet API

**Comment by codecat** [comment]
Actually, the bug is that they appear in the json. They are not currently callable from Openplanet to avoid people cheating. Maybe we can change this once school mode is released.
