### ISSUE TITLE
string::SubStr and wstring::SubStr have different behaviors

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#406]
I was doing `string(folder.FullDirName.SubStr(7))` as a way to get the extract directory of a FidsFolder with a path like: `<fake>\MemoryTemp\CurrentMap_EmbeddedFiles\ContentLoaded\Items\z983-waypoint_stickers_2022\waypoint_stickers_2022_1XL\waypoint_stickers_6_1XL\`.

Unexpectedly, I'd get an empty string (probably because of the length argument)

However, `string(folder.FullDirName).SubStr(7)` works fine. 

Not sure if this is a Nadeo thing or an Openplanet thing, but it'd be better if they both worked the same IMO.

**Comment by codecat** [comment]
Was this on Maniaplanet/Turbo or on TM? On TM, `string` and `wstring` are identical internally, they just have a slightly different API. But they should have the exact same behavior on substr.

**Comment by XertroV** [comment]
tm2020

**Comment by XertroV** [comment]
I think it makes sense given these API differences.

![image](https://github.com/openplanet-nl/issues/assets/1046448/6502d0ff-6826-476d-8e96-a1e2e2c23e07)
![image](https://github.com/openplanet-nl/issues/assets/1046448/ce8b8eba-6ba0-4a4e-9c13-0328c17327a4)
