### ISSUE TITLE
Implement UI slider flags

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#411]
Would be nice to have Imgui's flags for sliders (https://oprypin.github.io/crystal-imgui/ImGui/ImGuiSliderFlags.html)

I tried looking through the official Dear Imgui wiki, but it's kind of a mess. These flags are mentioned in some issues but I didn't find a full list of them except on other sites. I'm assuming they are all there, just not implemented for Openplanet's `UI`.

**Comment by Phlarx** [comment]
The "official list" is here:
https://github.com/ocornut/imgui/blob/240ab5890b2e8da294937a1710b021ac3f271472/imgui.h#L1633-L1647

(in my experience, that header file *is* the documentation)

**Comment by ezio416** [comment]
Nice thank you, I was definitely having trouble finding that
