### ISSUE TITLE
Turbo hook registers incorrect

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#412]
It seems like the register names for hook functions in turbo are wrong.

* (argument name) is (actual register)
* eax is edi
* ebx is esi
* ecx is ebp
* edx is esp
* esi is edx
* edi is ecx
* ebp is ebx

Examples in vehicle state On Vehicle Update Hook PR

**Comment by XertroV** [comment]
Is it possible this solves #391 and #410 as well?

**Comment by codecat** [comment]
No.
