### ISSUE TITLE
Markdown newline `\` ignored on dev site

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#414]
Example when writing a plugin description:
```
This is line one.\
This is line two.
```
On a plugin's "public page," this will look like:
```
This is line one.\ This is line two.
```

If it followed markdown rules, it should look like so:
```
This is line one.
This is line two.
```

**Comment by sylae** [comment]
P sure backslashes at the end is a rarely followed commonmark thing

Putting two spaces at the end (SPACE SPACE CR LF) will do what u want it to do

**Comment by ezio416** [comment]
Thanks I didn't know that. However I still feel if the text box says it supports Markdown, it should support all of it

**Comment by codecat** [comment]
I've never seen the backslash method before, so I don't think it's super common. Either way, will close this since a workaround was found.
