### ISSUE TITLE
MP4 Crash if nod explorer has Editor node open while recording a ghost in mediatracker

### ISSUE THREAD

**Issue by LinUwUxCat** [openplanet-nl/openplanet-issues#415]
In ManiaPlanet, if you go in mediatracker (either replay editor or in-map mediatracker), the Editor variable represents the mediatracker editor, and it works properly. 

However, if you then try to record a ghost, the game will crash if you have that node open, or if you try to open it while recording.

https://github.com/openplanet-nl/issues/assets/46047705/35d63883-5c09-4c03-a664-01317750b30b

**Comment by LinUwUxCat** [comment]
LogCrash : [LogCrash_0000000140B528F0.txt](https://github.com/openplanet-nl/issues/files/13911385/LogCrash_0000000140B528F0.txt)

**Comment by codecat** [comment]
There's a good chance this is a Nadeo bug that we can only fix by removing the faulting property from visibility in the Nod Explorer. Will take a look when I have some time.

**Comment by codecat** [comment]
I fixed this by hiding some properties from `CGameCtnMediaTracker` in nod explorer: `ReplayTime`, `BlockStart`, `BlockEnd`, `StereoSepMax`. They are still available to scripts (**if** they don't crash the game - I have not tested this).
