### ISSUE TITLE
Trackmania does not launch when Openplanet installed

### ISSUE THREAD

**Issue by embedcat** [openplanet-nl/openplanet-issues#416]
I have installed Openplanet 1.26.12 (latest). Steam version Trackmania just not launch with no error. When removing Openplanet, Trackmania works well.
I tried reinstall Trackmania and Openplanet - there is the same issue.
OS: Windows 11

**Comment by codecat** [comment]
Try installing this, then restart your computer: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by embedcat** [comment]
Yes, it works! Thanks!
