### ISSUE TITLE
missing preprocessor causes game to hang on load

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#420]
In resolving a merge conflict, I somehow deleted a `#if TMNEXT` that was before `#elif MP4` and `#endif`. The last lines of the log did show this error:

```
[    ScriptEngine] [20:04:27]  Unexpected #elif on line 137
[    ScriptEngine] [20:04:27]  Unexpected #endif on line 163
```

However, this made the game hang indefinitely on the "Connecting" screen when I tried to boot it up. This should instead just throw an error and refuse to compile the plugin

**Comment by codecat** [comment]
I am unable to reproduce with this test plugin:
```asc
void Main()
{
	print("No");
#elif MP4
	print("Yes");
#endif
}
```
Do you have any more details on this issue?

**Comment by ezio416** [comment]
I also can't reproduce with your case so it seems more specific than that. I pulled this from a version of Current Surfaces where it originally broke, and this minimal case does cause the game not to load:

```Angelscript
string MaterialName(EPlugSurfaceMaterialId mat) {
    return "";
}

#elif MP4
string MaterialName(CAudioSourceSurface::ESurfId mat) {
    return "";
}
#endif
```

Maybe it has to do with defining a function multiple times since when preprocessors are unexpected, they end up being ignored

**Comment by codecat** [comment]
I am still unable to reproduce this with your code:

![image](https://github.com/openplanet-nl/issues/assets/136534/2ad57e33-4c37-4c30-b671-4d68649d8e46)

**Comment by ezio416** [comment]
I can't reproduce this anymore myself, maybe this was fixed in a recent update
