### ISSUE TITLE
Dev:: read/write methods for mat4, iso4

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#421]
Please add Dev:: read/write methods for mat4, iso4 (and get/set offset), oh and mat3, too

**Comment by codecat** [comment]
The game generally doesn't use mat4. `Dev::ReadIso4`, `GetOffsetIso4`, `Write`, and `SetOffset` are already implemented.

**Comment by XertroV** [comment]
Ahh, I think I might have assumed Iso4 didn't have those methods because they don't exist for mat3/mat4. Sorry about that
