### ISSUE TITLE
Game freeze when unexpected audio type loaded

### ISSUE THREAD

**Issue by sylae** [openplanet-nl/openplanet-issues#423]
```angelscript
IO::File file(IO::FromStorageFolder("custombonk.wav"), IO::FileMode::Read); // actually an mp3
@bonkSound = Audio::LoadSample(file.Read(file.Size()));
file.Close();
```
not the end of the world but it'd be nice to check magic or something to verify a file is what the extension says it is, or at least gracefully fail (ie in the above example, setting `@bonkSound` to null as it does if the file doesnt exist).

**Comment by codecat** [comment]
Thanks, I've fixed this bug for the next release.

Also, I've added `Audio::LoadSampleFromAbsolutePath` to do what you're trying to do here, more efficiently. Your current code will load the file into memory twice which is not ideal.
