### ISSUE TITLE
reloading a dependency with a shared enum where a duplicate value is introduced crashes the game

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#425]
EDIT: I have JIT enabled, so maybe all bets are off. Just got a crash reloading with a totally different compile error, and another with no compile error.

situation:

- was updating Better Room Manager and had to pull in some merges. At the same time, I'd added RoyalStars. 
- there's an explicitly numbered enum and I had the pictured situation. 
- upon reloading, the game crashed. 
- it did give me a compile error in the logs, it was when it was compiling dependent plugins that it crashed. 

might be an angelscript bug, not sure. Also not sure how hard a minimal test case would be to put together.

![image](https://github.com/openplanet-nl/issues/assets/1046448/70c5779e-6fc8-4b9b-861c-a81fc67e90e6)

**Comment by codecat** [comment]
I am unable to reproduce. (JIT off)
