### ISSUE TITLE
Create Map does not work in 1.26.12

### ISSUE THREAD

**Issue by Ozmao** [openplanet-nl/openplanet-issues#426]
The function Create Map doesn't work as intended.

**Recreation steps:**
1. Open Plugin drop down
2. Press Create a new map
3. Set the properties
4. click Create

**Conclusion:**
this will close the menu and not generate a map 

To exclude that this may be an isolated case I scurried reddit and found a post detailing the same issue: https://www.reddit.com/r/TrackMania/comments/19434vo/does_the_create_a_new_map_button_work_for_others/

**Comment by codecat** [comment]
This has been fixed already, just haven't released the update yet.
