### ISSUE TITLE
add `Signed` to `Meta::Plugin`

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#428]
Would just be nice to have a way to check if another plugin is signed

**Comment by codecat** [comment]
What's the exact purpose of this? So that I know what information you really need.

**Comment by ezio416** [comment]
I'm displaying lists all installed plugins, and seeing which are signed or not would be a useful bit of information to add to that. I'd also like the option to uninstall plugins (I made a PR to Plugin Manager for that) and checking if one is signed would add more safety to that as well

**Comment by ezio416** [comment]
It may also be useful to see if a plugin is signed the old way (.sig) or the new way (.manifest), but this is definitely less important than just seeing if it's signed at all

**Comment by ezio416** [comment]
Thank you!
