### ISSUE TITLE
Unable to load maps after Rally Car update.

### ISSUE THREAD

**Issue by Haiku586** [openplanet-nl/openplanet-issues#429]
![image](https://github.com/openplanet-nl/issues/assets/161489246/aaf17b46-4ad4-4194-9178-16e52b825dd5)

**Comment by codecat** [comment]
This looks like a Trackmania issue to me, not an Openplanet issue. I'd recommend reporting this on the Trackmania or the Ubisoft Discord instead.

Actually, I guess this error can show up if you haven't updated your game yet?
