### ISSUE TITLE
Attempting to assign an array to a variable typed for enum crashes on compile

### ISSUE THREAD

**Issue by ArEyeses79** [openplanet-nl/openplanet-issues#430]
Example code that causes crash when compiled:
```
enum A {}
A a = {};
```
This just shows compilation failed warning on variables typed for int; haven't tested other types

**Comment by codecat** [comment]
I have [reported this on the Angelscript forum](https://www.gamedev.net/forums/topic/715661-crash-on-invalid-enum-usage/).
