### ISSUE TITLE
this map crashes openplanet

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#436]
Trying to load this map in solo causes a crash in openplanet.dll. I don't know if this is a problem with some plugin (e.g., trying to access RootMap when it doesn't load), but i didn't see anything specifically in logs besides normal loading map stuff. 

The mod pack has been updated manually and doesn't work. An earlier version with the mod file partially changed (there's a few references to update) does *not* cause the crash.

If you can't reproduce this it's fine to close this issue.

![image](https://github.com/openplanet-nl/issues/assets/1046448/e9f75489-68d3-4405-a6b3-3b58755ddf5e)

[Thread_of_Rallyadne_fixed.Map.zip](https://github.com/openplanet-nl/issues/files/14502463/Thread_of_Rallyadne_fixed.Map.zip)

**Comment by codecat** [comment]
Please include your LogCrash file as well.

**Comment by codecat** [comment]
I am unable to reproduce. I'd still ask to see a LogCrash file of this though.

**Comment by XertroV** [comment]
There wasn't a logcrash because it was an openplanet crash (never had a logcrash generated in that case).

However, I think it was something on my end. I can't reproduce it anymore.

**Comment by codecat** [comment]
Typically when this error shows, a logcrash file is in the process of being written. Perhaps the broken state of the process didn't have enough strength left to safely perform IO. :(
