### ISSUE TITLE
Add more file types for `Audio` namespace and add documentation

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#440]
It seems like I can only load audio of types `aiff`, `flac`, `mp3`, and `wav`. It would be nice to also be able to play other common formats like `aac`, `amr`, `m4a`, `m4r`, `mux` (commonly used in TM maps, seems to be an `ogg` type based on loading a nod from a `mux` file), and `ogg`. These supported types should also be documented (I was surprised to find `aiff` is supported but not `mux` and only found these by testing).

`Audio::LoadSampleFromAbsolutePath()` is also not documented.

**Comment by codecat** [comment]
Thanks, I have updated the documentation and [LoadSampleFromAbsolutePath](https://openplanet.dev/docs/api/Audio/LoadSampleFromAbsolutePath) is now displayed.
