### ISSUE TITLE
crash on assert: tempVariables.GetLength == 0

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#442]
![image](https://github.com/openplanet-nl/issues/assets/1046448/e9753831-fc0f-47da-a947-dcd62892ba70)

Happened on reloading E++.

Clicked ignore a bunch. There was a different message after some repeats of that assertion, but I clicked ignore too quickly to see it. Then the game crashed.

**Comment by XertroV** [comment]
okay on restarting the game I got the original assertion error then a few more.

![image](https://github.com/openplanet-nl/issues/assets/1046448/2ac75317-b93e-4ec9-9077-48c43b403a0c)
![image](https://github.com/openplanet-nl/issues/assets/1046448/1cb51aba-1b87-4239-896e-400497ee5947)
![image](https://github.com/openplanet-nl/issues/assets/1046448/4cf897b4-7891-4ece-9d49-acf081b45a4a)


```angelscript
        // this causes assertion errors
        // protected ObjInMap@[]@[] _Macroblocks;
        // const ObjInMap@[]@[]@ get_Macroblocks() { return _Macroblocks; }
        // this does not
        protected ObjInMap@[][] _Macroblocks;
        const ObjInMap@[][]@ get_Macroblocks() { return _Macroblocks; }

        protected void AddToMacroblock(ObjInMap@ b) {
            if (b.mbInstId < 0) return;
            while (b.mbInstId >= _Macroblocks.Length) {
                _Macroblocks.InsertLast({});
                dev_trace("_Macroblocks length: " + _Macroblocks.Length + " for mbInstId: " + b.mbInstId);
            }
            _Macroblocks[b.mbInstId].InsertLast(b);
        }
```

**Comment by codecat** [comment]
So this is related to an array of arrays as handles? Can we find a minimal reproduction case w/o the use of Openplanet-specific API's to report on the Angelscript forum?

**Comment by XertroV** [comment]
Reported here: https://www.gamedev.net/forums/topic/715669-4-assertion-errors-with-nested-lists-of-handles/

Repro:

```angelscript
class Cache {
    Cache() {

    }

    protected Obj@[]@[] _Blah;
    const Obj@[]@[] get_Blah() {
        return _Blah;
    }

    protected void AddObj(Obj@ o) {
        while (o.pos.x >= _Blah.Length) {
            _Blah.InsertLast({});
            break;
        }
        _Blah[o.pos.x].InsertLast(o);
    }
}

class Obj {
    nat3 pos;
    Obj(nat3 pos) {
        this.pos = pos;
    }
}
```
