### ISSUE TITLE
Add `Transpose` method to `mat` types.

### ISSUE THREAD

**Issue by msmorgan** [openplanet-nl/openplanet-issues#445]

**Comment by codecat** [comment]
Not sure what you mean. We have [`mat4::Translate`](https://openplanet.dev/docs/api/mat4/Translate) and [`mat3::Translate`](https://openplanet.dev/docs/api/mat3/Translate) to create translation matrices.

**Comment by codecat** [comment]
Oh, I misread `Transpose` as `Translate`. I see, disregard my comment :)
