### ISSUE TITLE
Add typedef support to AngelScript

### ISSUE THREAD

**Issue by msmorgan** [openplanet-nl/openplanet-issues#446]
Other language features that could be useful:

- `abstract`
- Shared mixin classes
- Treat imported functions as shared

**Comment by codecat** [comment]
This is something you'll want to suggest on the Angelscript forum: https://www.gamedev.net/forums/forum/34-angelcode/

**Comment by msmorgan** [comment]
But these are on their doc site as language features?

Edit: I see typedefs aren't as useful as I hoped since they can only represent primitives.

**Comment by msmorgan** [comment]
To add to this list: [`weakref` support](https://www.angelcode.com/angelscript/sdk/docs/manual/doc_addon_weakref.html)
