### ISSUE TITLE
DEPENDENCY_ preprocessor doesn't support `+`?

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#449]
I have my dev copy of editor++ in a plugin folder called `editor++-dev`. Is there a way to do DEPENDENCY_ preprocessor checks for a plugin with this ID?

**Comment by XertroV** [comment]
So I see in #355 you linked the ccpc code and yeah + won't be supported. I have changed the folder name on my end so it's not really a big deal, but it'd be nice if there was some handling of non-supported characters (e.g., by dropping them or replacing them all with underscores)

**Comment by codecat** [comment]
You're right, `+` should also be replaced with `_`.
