### ISSUE TITLE
Curious order of operation mismatch (intuition vs implementation)

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#455]
```angelscript
void Test() {
  nat3 v1 = nat3(1, 2, 3);
  auto buf = MemoryBuffer(100);
  buf.Write(v1.x);
  buf.Write(v1.y);
  buf.Write(v1.z);
  buf.Seek(0);
  nat3 v2 = nat3(buf.ReadUInt32(), buf.ReadUInt32(), buf.ReadUInt32());
  if (v1.x != v2.x) throw("Mismatching!");
}
```

I would expect this to work correctly (i.e., v2 == v1)

However, I found that `v2 == nat3(v1.z, v1.y, v1.x)`

Reading the nat3 like this works:
```angelscript
    auto x = buf.ReadUInt32();
    auto y = buf.ReadUInt32();
    auto z = buf.ReadUInt32();
    v2 = nat3(x, y, z);
```

Is this even a bug? I would have thought arguments were evaluated in order, but doesn't seem like it. 

Might be something to report to angelscript forums, but it'd also be a breaking change to fix it if anyone relied on this behavior for some reason.

**Comment by codecat** [comment]
This is not a bug, and is intended [according to the Angelscript documentation](https://www.angelcode.com/angelscript/sdk/docs/manual/doc_expressions.html#function):

> If a function takes more than one argument, the argument expressions are evaluated in the reverse order, i.e. the last argument is evaluated first.
