### ISSUE TITLE
reload of plugin (ctrl + r) can occur in a text field

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#460]
So there's the ctrl getting stuck bug that's well known. You can go to another window, come back to TM, and pressing R will reload a plugin. 

had an interesting case today testing Map Together chat in the editor, where, while typing in a imgui text field, the shortcut for reload plugin would trigger. 

calls to user32's GetAsyncKeyState showed ctrl and alt as unpressed, but just typing 'r' was enough to reload. 

the shortcut to bring up chat is shift + enter and the enter press is blocked. 

I think I *always* went to another window before this bug was triggered.

**Comment by codecat** [comment]
Was there another issue for the "ctrl getting stuck" bug? I couldn't find one, but both problems mentioned in this issue should be fixed.
