### ISSUE TITLE
Dev::Hook register mismatch in TM Turbo

### ISSUE THREAD

**Issue by Mystixor** [openplanet-nl/openplanet-issues#466]
In TM Turbo the hooked register is being interpreted incorrectly. Openplanet currently takes the register names on the left and then returns the values of the registers on the right in reality:

"eax" -> EDI-register
"ebx" -> ECX- or ESI-register
"ecx" -> EBP-register
"edx" -> ESP-register
"esi" -> EDX-register
"edi" -> ECX- or ESI-register
"ebp" -> EBX-register
"esp" -> unsupported
"eip" -> unsupported

For the "ebx" and "edi" register names I cannot say for sure which one is which as these registers have the same value between both of them in all my hook locations.

**Comment by XertroV** [comment]
Already completed in https://github.com/openplanet-nl/issues/issues/412 -- but I think we need a new turbo release for it to go live.

**Comment by Mystixor** [comment]
Aha, I thought I remembered something but couldn't find an open issue anymore. A new release would be appreciated 👍

**Comment by codecat** [comment]
Re-opening this as I don't think I properly tested the last fix.

**Comment by Mystixor** [comment]
I just noticed that the automatic OP update notification didn't work on my installation, I was still on 1.26.0. Upgraded to 1.26.14 manually now and it seems to be fixed. Sorry for causing confusion.

**Comment by codecat** [comment]
Sounds good, thanks for confirming!
