### ISSUE TITLE
add `IO::MoveFolder`

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#472]
Maybe this could instead be `IO::Rename` that could work for files and folders, but I think MoveFolder would be more consistent with existing functions

**Comment by codecat** [comment]
The following code works for me:
```asc
auto path = IO::FromStorageFolder("Test");
auto newPath = IO::FromStorageFolder("Test_Moved");

IO::CreateFolder(path);
{
	IO::File f(path + "/test.txt", IO::FileMode::Write);
	f.WriteLine("Hello world");
}
IO::Move(path, newPath);
```
I did however change `IO::Move` to use `MOVEFILE_WRITE_THROUGH`, but that shouldn't matter too much if you're not immediately observing the directory.

**Comment by ezio416** [comment]
This snippet does work, my bad. I made the issue based on the discord convo but hadn't actually tested it myself.
