### ISSUE TITLE
Missing UI::SeparatorText mapping

### ISSUE THREAD

**Issue by nicoell** [openplanet-nl/openplanet-issues#479]
There's currently no mapping for ImGui::SeparatorText, which is a very hand and easy to use widget to organize menus.
![tpV0Nl7VvP](https://github.com/openplanet-nl/issues/assets/4254495/5c98a2c0-3bf5-455b-a554-c4fe6f408958)

**Comment by codecat** [comment]
What a coincedence, I actually found this function earlier in the week and realized we had no bindings for it, and was gonna add it regardless 😅
