### ISSUE TITLE
1.26.21: `UI::BeginChild("blah", vec2(-1, 140), true, UI::WindowFlags::AlwaysVerticalScrollbar | UI::ChildFlags::AlwaysAutoResize)` throws 

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#483]
1.26.21: `UI::BeginChild("blah", vec2(-1, 140), true, UI::WindowFlags::AlwaysVerticalScrollbar | UI::ChildFlags::AlwaysAutoResize)` throws:
`UI assertion failed: (window_flags & ImGuiWindowFlags_AlwaysAutoResize) == 0 && "Cannot specify ImGuiWindowFlags_AlwaysAutoResize for BeginChild(). Use ImGuiChildFlags_AlwaysAutoResize!"`

**Comment by codecat** [comment]
Use the child flags parameter instead of the window flags parameter for child flags.

**Comment by codecat** [comment]
For clarification, this should be:
```asc
UI::BeginChild(
  "blah",
  vec2(-1, 140),
  UI::ChildFlags::AlwaysAutoResize | UI::ChildFlags::Border,
  UI::WindowFlags::AlwaysVerticalScrollbar
);
```

**Comment by XertroV** [comment]
ah so the bool was coerced and no compile error thrown

**Comment by XertroV** [comment]
Maybe function signature changes should be added to the changelog
