### ISSUE TITLE
Nod Explorer QoL

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#491]
Some QoL nod explorer features would be nice (or exposed so I can write a plugin to do them)

- autoclose tabs on close window
- autoclose tabs on returning to main menu
- close tab with kb sortcut

**Comment by codecat** [comment]
Tabs shouldn't autoclose at all, it would be inconsistent and potentially confusing.

I've added a new "Tabs" menu to Nod Explorer which should hopefully be useful:

![image](https://github.com/openplanet-nl/issues/assets/136534/251c3360-548e-42a5-841b-a6f6e64b6cab)

I'll need to think about how a Ctrl+W shortcut should be implemented -- it would be nice to have this built in to **all** closable ImGui tabs.
