### ISSUE TITLE
changing audio playback device does not work

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#496]
It doesn't matter what I set it to or what my primary Windows audio device is, I always have to restart the game to change the audio device. I'm on 1.26.25, but this has been an issue for a very long time, I just forgot about it and also forgot the setting even existed.

**Comment by XertroV** [comment]
As another data point, changing audio devices via openplanet works fine for me (on my main pc at least)

**Comment by codecat** [comment]
I am also unable to reproduce this issue, using this test plugin as a way to play audio:

```asc
Audio::Sample@ g_sample;

void Main() {
	@g_sample = Audio::LoadSample("Kick.wav");
}

void RenderMenu() {
	if (UI::MenuItem("Play kick")) {
		Audio::Play(g_sample);
	}
}
```

Do you see this in your log when you switch interface?

![image](https://github.com/openplanet-nl/issues/assets/136534/6aded798-f266-4ae4-aeba-9489c9e9f12b)

**Comment by ezio416** [comment]
My bad, I must have been doing something wrong, this setting does work
