### ISSUE TITLE
Openplanet.dev | Profiles | YouTube Channel ID Input Requires Manual `/channel/` Prefix

### ISSUE THREAD

**Issue by st-AR-gazer** [openplanet-nl/openplanet-issues#502]
When entering a channel ID, users are required to manually prepend `/channel/` to the ID as it is appended directly. This behavior seems unintended based on the provided instruction: `Type your channel ID or your @ handle, for example: @RickAstleyYT`.

**Current Behavior:**
- Users must input `/channel/` before the channel ID.
- Example: To access my YT channel I have to enter `/channel/UCb_gg4hhuK-Q5JEcebg1Lbw`, whilst what seems intended is `UCb_gg4hhuK-Q5JEcebg1Lbw`.

**Expected Behavior:**
- Users should be able to input only the channel ID without additional prefixes.
  - Also note that entering `/channel/` is not required when accessing a YouTube Channel through a handle; this works: `https://www.youtube.com/@ar...........................`
- The base URL should be assumed to be `https://www.youtube.com/channel/` instead of `https://www.youtube.com/`, when handling channel IDs.

**Visual Reference:**
![Channel ID Issue](https://github.com/openplanet-nl/issues/assets/132480072/0e9a10b6-c26f-4e8c-a1ec-6ff3ea6080b8)

**Proposed Solution:**
- Update the input handling to automatically assume the base URL as `https://www.youtube.com/channel/` when a plain channel ID is entered.

**Comment by codecat** [comment]
Is there any reason you'd prefer to use the channel ID over the handle?

**Comment by st-AR-gazer** [comment]
Not really, it was more that this seems like a bug that exists and that should be known.
(I don't really like to use mine since it has about 15 hundred dots "." after 'ar' 🙃)
