### ISSUE TITLE
Discord | Commad | Improving the discord .log command

### ISSUE THREAD

**Issue by st-AR-gazer** [openplanet-nl/openplanet-issues#507]
On the discord the .log command is used to well, direct users on how to get an Openplanet .log file. However, @phlarx brought up a good point about this, it should probably also include some statement about the Openplanet-Old.log file too.

Current return:
``
You can find Openplanet's log file in `C:/Users/Username/OpenplanetNext/Openplanet.log`. (Alternatively, replace `OpenplanetNext` with `Openplanet4` or `OpenplanetTurbo` depending on whether you are running Openplanet on Trackmania, Maniaplanet, or Trackmania Turbo.)
``

Proposed changes:
``
You can find Openplanet's log file in `C:/Users/Username/OpenplanetNext/Openplanet.log`. If you've reopened the game after the game has been closed you can instead check the `Openplanet-Old.log` for the previous game sessions log. 
For different game versions, replace `OpenplanetNext` with `Openplanet4` or `OpenplanetTurbo` depending on whether you are running Openplanet on Trackmania, Maniaplanet, or Trackmania Turbo.
``

**Comment by codecat** [comment]
I've added this line:
> If you are looking for the log of the previous session (the last time you shut down the game), there is also `Openplanet-Old.log`.
