### ISSUE TITLE
`opEquals()`, `opIndex()`, and multiple other functions missing for `wstring`

### ISSUE THREAD

**Issue by CodyNinja1** [openplanet-nl/openplanet-issues#508]
It would be nice if we could have most functions available in `string`, be also available in `wstring`, like `opEquals()`, and `opIndex()`

**Comment by codecat** [comment]
Generally, I recommend casting `wstring` to `string` if you need to do complex operations on it, for compatibility sake. Internally, `wstring` is just `string` nowadays anyway.

But I did add `opCmp` for string comparisons now.
