### ISSUE TITLE
allow plugin to unload itself, add `Meta::ReloadPlugin()`

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#510]
A plugin can be unloaded from another plugin, but why not itself? There are two use cases I could see this being useful in:
- reload itself to aid in development (kind of a duplicate of #154 except I think it makes more sense for it to be `Meta::ReloadPlugin(plugin)` instead of a member of `Meta::Plugin`)
- if a user has inadequate permissions then we can just stop the plugin completely to:
    - save some resources
    - save a bit of development work, i.e. if a plugin requires club access then I have to write in a bunch of things to hide the plugin from the user, whereas if it were unloaded then I don't need to do anything

For `Meta::ReloadPlugin()`, if implemented I feel it should return a new `Meta::Plugin`

**Comment by codecat** [comment]
I think the permissions thing could potentially be done in `info.toml` as well. 🤔

**Comment by ezio416** [comment]
I should've asked for this originally, but could you add the option for plugins to reload themselves as well?

**Comment by codecat** [comment]
Done!
