### ISSUE TITLE
`Meta::Plugin.SignatureLevel` inaccurate for old signature method

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#513]
For plugins signed the old way (`.sig` per file instead of the single `.manifest`), it shows they are unsigned (`-1`). I'm thinking they could be like this (an enum would be even better):
- `-1`: unsigned (remain)
- `0`: old signature method
- `1`: new signature method (remain)
- `2`: school mode
- `10000`: official (remain)

Some signed plugins I have that are showing unsigned because of this:
- Checkpoint Counter
- Dashboard
- Default to World Region in Menu
- DossardPlus
- Drive Alone
- Extract Validation Replay
- Http Inspector
- Knockout Warning Remover
- Map audio fix (still a script btw, should probably be an official plugin by now)
- Medals Editor
- Ranked Total Points
- Spectators
- Style Manager
- Ultimate Medals

**Comment by codecat** [comment]
This is not possible to do because in theory every file could have a different signature. Instead, I have added `HasManifest` which you can use to check if the plugin has a manifest file (and whether `SignatureLevel` is a "valid" value)
