### ISSUE TITLE
`OnMouseWheel` not called when mouse is over a UI window

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#518]
I'm trying to make a slider that responds to the mouse wheel, however when my cursor is over a UI window, `OnMouseWheel` is never called. Ideally there can be something similar to `UI::GetMousePos` for the wheel, but it would also be nice to have the callback work in this regard. Maybe this is related to #6?

**Comment by codecat** [comment]
I have added `UI::GetMouseWheelDelta` and `UI::GetMouseWheelDeltaHor`.
