### ISSUE TITLE
add metadata to `IO::File`

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#521]
There is a way to check a file's modify time through another IO function, but currently there's no way to check creation or access times or even change any of these manually. I think it would make sense to add these to `IO::File`, and if feasible, add ways to change these, though changing them would be a fairly niche use case.

Other metadata may also be useful but I can't think of any right now

**Comment by codecat** [comment]
What's your use case for modifying the timestamps?
