### ISSUE TITLE
`MwFastArray<float>` is not mutable when non-const

### ISSUE THREAD

**Issue by CodyNinja1** [openplanet-nl/openplanet-issues#523]
For example, `CFuncKeysReal` (in MP4) has `MwFastArray<float> Ys`.
Trying to modify any of this array's items has the changes reverted next frame.
```angelscript
void Render()
{
    auto wagon = cast<CPlugTrainWagonModel>(GetWagonFromFileName("Loco.Wagon.gbx")); // GetWagonFromFileName gets CMwNod for wagon in Valley/Media/Trains
    CFuncKeysReal@ FuncKeys = wagon.AccelCurve;

    print(FuncKeys.Ys[0]); // Change is reverted next frame.
    FuncKeys.Ys[0] = 1000;
    print(FuncKeys.Ys[0]);
}
```

**Comment by codecat** [comment]
This sounds like a bug - I will investigate.

**Comment by CodyNinja1** [comment]
Here is the `GetWagonFromFileName()` function:
```angelscript
CMwNod@ GetWagonFromFileName(const string&in filename)
{
    auto file = Fids::GetGame("GameData/Valley/Media/Trains/" + filename);
    auto nod = Fids::Preload(file);
    return nod;
}
```
Do note that only `Loco.Wagon.gbx` has a non-null `AccelCurve`.

**Comment by CodyNinja1** [comment]
This issue appears to have been a programming mistake on my end, sorry for any inconvinence.

**Comment by codecat** [comment]
Good to know, thanks for the update. Can you let me know what the mistake was?

**Comment by CodyNinja1** [comment]
My mistake was that I used ImGui's input fields incorrectly, so nothing really related to the MwFastArray itself.
