### ISSUE TITLE
Text::StripFormatCodes empty link oversight

### ISSUE THREAD

**Issue by Miltant** [openplanet-nl/openplanet-issues#528]
I see a bug in the regex powering StripFormatCodes that was recently posted on the Openplanet Discord (`\$([0-9a-fA-F]{1,3}|[iIoOnNmMwWsSzZtTgG<>]|[lLhHpP](\[[^\]]+\])?)`): links with an empty uri in brackets get the $ and letter stripped, but the brackets remain.

For example with "Open$l[]planet":
`Text::StripFormatCodes` output: "Open[]planet"
Game rendering: "Open[planet]()"

**Comment by codecat** [comment]
Maybe it renders like this in Maniaplanet? It doesn't actually render any link in Trackmania. Either way, fixed 😊
