### ISSUE TITLE
crash from nvg

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#529]
![image](https://github.com/user-attachments/assets/daae9d39-c513-46fc-a139-53c9c700cbcc)

Not sure what caused the assertion failed (besides what the error msg says)

I was just drawing some simple shapes. Maybe an edge case of 3d transformations or something?

error for searching: `numIndices < D3D->VertexBuffer.MaxBufferEntries`

**Comment by codecat** [comment]
I think you're drawing too many things? The current limit is 1,000,000 vertices. We can increase that, but I'm curious if you know whether you actually hit this or you accidentally hit this much.

**Comment by XertroV** [comment]
I wasn't anywhere near 1m vertices (well, assuming my code was not doing something stupid). IDK how long a loop would take but I don't remember a long freeze before the error.

In any case, it hasn't happened again, just wanted to mention it at the time. 

The code that generated it (or seemed to) has been fine since (and handling much more than it was before).

Is it possible some weird singularity-like event cause something weird?

Additionally, I might have been fiddling with memory and IDK if maybe something got corrupted (e.g., the length of a buffer, since it seems like the assert is just checking a length)

**Comment by codecat** [comment]
Closing for now. Let me know if you can run into this somewhat reliably and/or you need the vertex limit increased.
