### ISSUE TITLE
School mode: Flag School mode-only plugins in the plugin manager

### ISSUE THREAD

**Issue by davidbmaier** [openplanet-nl/openplanet-issues#534]
Make sure it's clearly visible and intuitive for the average user which plugins are only available in School mode.

Maybe via a special tag or disclaimer - if the website already supports this, just make sure the in-game plugin manager looks similar.

**Comment by codecat** [comment]
Some parts of this are already implemented, such as a big warning on the description of the plugin on the website:

![image](https://github.com/user-attachments/assets/44a85948-f954-4238-9203-5499ca9cb901)

And part of the plugin's tags:

![image](https://github.com/user-attachments/assets/7631abd8-7e57-4bf6-a59e-0fbbd94235b6)

This still needs to be added properly to the plugin manager though. We may also want some filters for the plugin manager. Maybe this also ties in with #501.

**Comment by codecat** [comment]
The plugin manager now looks like this:

![image](https://github.com/user-attachments/assets/e034fcb4-e7d7-472b-a1d9-a8df63fb9082)
