### ISSUE TITLE
Plugin Plugin_MapAudioFix crashes the game on version 1.26.31 when opening a Non-Stadium base map.

### ISSUE THREAD

**Issue by glocom** [openplanet-nl/openplanet-issues#542]
When opening older maps which use the No-Stadium base map (with the sound bug) the game crashes.
Some example maps are:
- TOTD of 24-dec-2022 (https://trackmania.exchange/maps/85847/ccp24-the-night-before-christmas-ft-zengo)
- TOTD of 23-feb-2021 (https://trackmania.exchange/maps/24667/cornertech)

This happens on Openplanet version 1.26.31 (2024-08-12) for TM2020.

Game version: 

```
BuildInfo
=========

TitleInfo
---------

* Commit: "e0a17ecbc10c5ea18ecfe767bc938b8ec7bfb05d"
* Date: "2024/07/02 15:47"
* Version: "202407021547"
* TitleUpdate: "13.2"

PlatformInfo
------------

* Name: ::ESystemPlatform::UPlay
* Sku: ::ESystemSkuIdentifier::Unknown
* Family: "PC"
* FirstParty: 0
* ExeVersion: "2024-07-02_14_35"
```

There's also a LogCrash file created by TM:
[LogCrash_000000000131C961.txt](https://github.com/user-attachments/files/16665534/LogCrash_000000000131C961.txt)

When the plugin Plugin_MapAudioFix.as is disabled, the game doesn't crash.

**Comment by codecat** [comment]
Looks like this was caused by the fix applied in #525. I'll revert that "fix" as clearly it wasn't the right fix. Thanks!
