### ISSUE TITLE
UI::PushID(const ?&in) doesn't work as expected

### ISSUE THREAD

**Issue by AurisTFG** [openplanet-nl/openplanet-issues#545]
When using ``UI::PushID`` with a non-string parameter, the function call compiles without errors but doesn't actually push the ID.

Happens on both pre-schoolmode and post-schoolmode versions of Openplanet.

### Code example:
```cpp
for (uint i = 0; i < arr.Length; i++)
{
    UI::PushID(i); // doesnt work, although compiles fine without errors
    UI::PushID(i + ""); // works

    // UI:Button etc..

    UI::PopID();
}
```

**Comment by codecat** [comment]
Not necessarily a bug; `PushID()` with any variable will use the address of that variable for the ID. In this case, it will use the address of `i`, which will never change. We could add a version of `PushID` that accepts an integer, just to support that.

**Comment by AurisTFG** [comment]
Ah, that makes sense then. Maybe it could be specified in the documentation by how exactly those two functions differ 🤔 
I now see that I can even do ``PushID(arr[i])``, which is pretty neat.
A 3rd variant of ``PushID`` could be cool, although appending `` + ""`` or passing ``arr[i]`` isnt a hassle so it's fine the way it is right now.

**Comment by codecat** [comment]
It’s not a hassle, but it does add unnecessary overhead, so I would like to get this fixed.
