### ISSUE TITLE
Failed assert when passing a string to `startnew(CoroutineFuncUserdata@ func, ref userdata)` when `ref` is expected to be a handle.

### ISSUE THREAD

**Issue by Mattynator0** [openplanet-nl/openplanet-issues#547]
![image](https://github.com/user-attachments/assets/c686d28f-f20b-49d4-bcb9-bf946bcb85f7)
![image](https://github.com/user-attachments/assets/dddeb46b-5461-4f43-8839-3507729c064a)

Also yes, I later realized that `CoroutineFuncUserdataString` exists. The bug exists nevertheless.

**Comment by codecat** [comment]
This reproduction can be simplified to:
```
void Main() { ref@ a = "a"; }
```

**Comment by codecat** [comment]
Reported here: https://www.gamedev.net/forums/topic/717451-failed-assertion-when-assigning-string-to-ref/
