### ISSUE TITLE
[1.26.31] some theme colors ignored

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#549]
Certain UI elements seem to remain a default color when applying a theme through the Overlay Style Manager. However, I'm putting this issue here as I don't think the manager is at fault - when I updated to the edge branch, my colors were kinda messed up immediately without applying a theme again. From what I can tell, it is just `TabActive` through `DockingPreview` that are being overridden to the default color somehow. Creating a new theme, manually changing the colors, then applying does seem to work, and applying a custom theme through Openplanet's settings also seems to work fine.

![Screenshot 2024-09-04 003858](https://github.com/user-attachments/assets/5d38460e-926d-4f0a-857c-8edfed5d62e2)
![image](https://github.com/user-attachments/assets/3a5d7d61-b4e1-4fae-87f8-5731be1ecb73)

**Comment by codecat** [comment]
The following colors were renamed upstream:
* `TabActive` => `TabSelected`
* `TabUnfocused` => `TabDimmed`
* `TabUnfocusedActive` => `TabDimmedSelected`

And some new colors were added as well. I don't think it's worth adding backwards compatibility for these, so we'll have to update the outdated styles.
