### ISSUE TITLE
School Mode maps export

### ISSUE THREAD

**Issue by st-AR-gazer** [openplanet-nl/openplanet-issues#550]
Would it be possible to get an Openplanet export that exports a list of the school mode maps where records can be uploaded? 
(I want to make a plugin that lists these maps so that they can be opened in solo/joined on a server easily from anywhere, but I couldn't find a proper 'list' with this info anywhere...)
Would be amazing to see this added :D

(also just a quick addendum, this is assuming ofc that there will be maps in the future that have a school mode exception but are not in the Openplanet school campaign)

**Comment by codecat** [comment]
You can use [`/api/config`](https://openplanet.dev/api/config), see the `wmuid` array. I don't think I will make a dedicated API for this.

**Comment by st-AR-gazer** [comment]
Ah, I didn't know that that existed. Should work well enough for my purposes :)
(Consider it if you ever add a 'school' api then, though most school stuff probably fit in Meta)
