### ISSUE TITLE
`Net::HttpRequest().SaveToFile()` doesn't save file when there are mixed slashes in file path.

### ISSUE THREAD

**Issue by CodyNinja1** [openplanet-nl/openplanet-issues#565]
e.g. when calling `request.SaveToFile("C:/Users/user/Documents/Maniaplanet\\Packs\\file.txt")` the file downloaded from the `request` doesn't save

**Comment by CodyNinja1** [comment]
the source of the mixed slashes usually comes from the fact that the `IO::From` functions return absolute paths with backslashes instead of forwardslashes

**Comment by codecat** [comment]
I can't reproduce this. This works fine for me:
```asc
void Main()
{
	auto req = Net::HttpGet("https://example.org/");
	while (!req.Finished()) {
		yield();
	}

	string path = IO::FromStorageFolder("test/foo.txt");
	req.SaveToFile(path);
	print("Done: " + path);
}
```
![image](https://github.com/user-attachments/assets/3d804286-1f6f-4e83-8225-e1e130f1eb0f)

![image](https://github.com/user-attachments/assets/73c7d58f-55d1-47fd-ae41-8ac72ca9a1af)

Note that I had to make the `test` folder myself first. Is that maybe the problem you're running into?

**Comment by CodyNinja1** [comment]
In my use case, which is downloading packs into the Packs folder, the Packs folder in `Documents/Maniaplanet/Packs/` always exists. Might be a wine/proton related issue since I am running maniaplanet on steam via proton?

**Comment by codecat** [comment]
That's definitely possible. I don't have a Linux machine to test this right now, unfortunately.

**Comment by CodyNinja1** [comment]
I do have a windows machine, I will test this shortly.

**Comment by CodyNinja1** [comment]
Sorry I got a bit sidetracked and forgot to report what happened on windows, the issue for me seems to be non-existent there.
