### ISSUE TITLE
Open trackmania again after updating

### ISSUE THREAD

**Issue by jurgenvdb** [openplanet-nl/openplanet-issues#567]
I know there has been an update that automatically closes the trackmania window when updating openplanet, but it would be a nice QOL feature to have an option to automatically launch the game again when closing/finishing the update window, just like the option to be able to open the README.

**Comment by codecat** [comment]
I thought there would be an existing Github issue for this but I can't find any now. Basically, this is not possible for several reasons:

1. Trackmania is available on more than one platform (Ubisoft Connect, Epic Games, Steam). This means we can't know for sure how to start the game. We may need to run a `uplay://` URI, a `steam://` URI, etc.
2. Starting `Trackmania.exe` is not a solution either: a lot of people have erroneously installed the game in multiple locations. If someone starts an outdated version of the game, it will either just start that outdated version, or it will start the game in a completely different location. This makes just starting the exe unreliable and potentially misleading.

So unfortunately, this is not possible to do right now. Of course you're more than welcome to come up with some solutions to these problems! 😊

**Comment by jurgenvdb** [comment]
on installation, you input the folder where trackmania is installed, wouldn't it be possible to use this trackmania.exe?

**Comment by codecat** [comment]
That's already answered by point 2 in my comment above 😊
