### ISSUE TITLE
`Size` is not a property of `Reflection::MwClassInfo()` on Turbo.

### ISSUE THREAD

**Issue by CodyNinja1** [openplanet-nl/openplanet-issues#569]
read title
![image](https://github.com/user-attachments/assets/6d0bf691-fb5d-4398-a629-b4c8aba726ec)
![image](https://github.com/user-attachments/assets/81cebb88-b8d6-4a0b-8252-d40a65a600aa)

**Comment by codecat** [comment]
The data does not exist in this version of the engine.
