### ISSUE TITLE
add a function parse date strings into unix timestamps

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#590]
This snipped gets repeated a lot, which is probably a lot of overhead for what it does. Would be better to have a native function for it
```asc
SQLite::Database@ cursedTimeDB = SQLite::Database(":memory:");
int64 DateFromStrTime(const string &in inTime) {
    auto st = cursedTimeDB.Prepare("SELECT unixepoch(?) as x");
    st.Bind(1, inTime);
    st.Execute();
    st.NextRow();
    st.NextRow();
    return st.GetColumnInt64("x");
}
```

**Comment by codecat** [comment]
Please be more descriptive

**Comment by XertroV** [comment]
Fair, I'm not exactly sure, I guess it's parsing a date string to a unix timestamp. It got added to mxrandom in the latest version, and the sqlite hacky date parse thing comes up from time to time.

Mostly I just wanted to make an issue so we had a way to track it and didn't forget.
