### ISSUE TITLE
Crash to desktop when using Time::FormatString

### ISSUE THREAD

**Issue by SilPho** [openplanet-nl/openplanet-issues#594]
When using Time::FormatString, it will crash Trackmania completely if the provided timestamp corresponds to a time beyond January 3000.
```
print("This succeeds:" + Time::FormatString("%c", 32500000000));
print("This crashes: " + Time::FormatString("%c", 33000000000));
```
I know this is an unlikely circumstance, but it did take me a while to track down when an unrelated bug caused my plugin to try and parse an unintendedly large number.

It's also not a clean crash to desktop, it leaves a ghost process running that continues to take up nearly 2GB of RAM each time, I had to use Resource Monitor, not Task Manager, to kill it.

**Comment by SilPho** [comment]
NaNInf pointed out that this seems to be fixed in an upcoming but currently unreleased patch. I can close this early if desired, or leave it here until the update drops.

**Comment by codecat** [comment]
Not sure - I will test this when I can.

**Comment by codecat** [comment]
This was fixed in the last edge update.
