### ISSUE TITLE
Loading plugin with setting description using single quotes with a space in it causes ctd

### ISSUE THREAD

**Issue by ArEyeses79** [openplanet-nl/openplanet-issues#596]
If the description attribute on a setting value, where single quotes (`'`) are used for the string, ~~is too long (only needs like 50~100 characters)~~ has a space in it then it causes ctd when that plugin is loaded.
This does not occur for ~~short~~ single-word descriptions using single quotes, and does not occur when using double quotes (`"`)

**Comment by ArEyeses79** [comment]
Update: Its not caused by length, but rather by having a space. I remember having issues about spaces in single quotes before...
that was https://github.com/openplanet-nl/issues/issues/310
In the `name=` field a space just ends the setting name rather than causing a crash wheras in description it causes ctd so this is worse xdd

**Comment by codecat** [comment]
Closing as duplicate
