### ISSUE TITLE
[bug?] some weird files appeared in the Pack explorer

### ISSUE THREAD

**Issue by AmazingBeu** [openplanet-nl/openplanet-issues#598]
Three files appeared *really* recently in the pack explorer of the Trackmania title pack `bf1b2533e25a2053969d0f5b0192c71dc95196f3`:

- `Scripts/Libs/Nadeo/TMGame/Modes/Base/UIModules/me/Modes/Base/UIModules/`
- `Media/Manialinks/Nadeo/Trackmania/Menus/Common/Nadeo/Trackmania/Menus/Common`
- `Media/Manialinks/Nadeo/Trackmania/Menus/Common/adeo/Trackmania/Menus/Common`

![image](https://github.com/user-attachments/assets/0305f743-201b-4ae2-8527-7bafabe37cf0)

files are 0 bytes sized once extracted.

File doesn't appear using a Gbx.Net app made by AurisTfg

**Comment by codecat** [comment]
I think this is a problem with some `FileHashes.txt` files out there. I noticed mine had this, and I think I got mine from the community.
```
91BFE084F6630D412CE34204731A5CF5CF
me\Modes\Base\UIModules\ø
```
I've confirmed this particular hash to exist in [Beu's file](https://openplanet.dev/file/100). (There are probably a lot more broken ones.)
