### ISSUE TITLE
Remove invalid format codes from string

### ISSUE THREAD

**Issue by Fort-TM** [openplanet-nl/openplanet-issues#605]
## Issue

`Text::OpenplanetFormatCodes` and `Text::StripFormatCodes` don't remove invalid format codes from a string, in this case a club tag, unlike the game and tm.io, who can render the tag correctly

## Information

The issue was noticed through Better Chat while in a MM game

![image](https://github.com/user-attachments/assets/38c09b6b-a979-4259-b856-2af04f3f2819)

Both the game and trackmania.io don't have any issues with it

![image](https://github.com/user-attachments/assets/02e837cf-9a0c-4764-98b5-5af8bed4dcf1)

![image](https://github.com/user-attachments/assets/8a77d756-4e8a-4e2f-8244-d9c8c6154475)

The full club tag is `$FF8$SB$EF0$RE$EB0$RE$FA0$RR`, with `$R` causing the issue

## Current behavior

This is what the OP functions related to format codes return when passed this club tag (tested in MP4 but should be the same in TM2020)
```log
[   ScriptRuntime] [  LOG] [08:48:38] [Test]  Text::StripFormatCodes: B$RE$RE$RR
[   ScriptRuntime] [  LOG] [08:48:38] [Test]  Text::StripNonColorFormatCodes: $FF8B$EF0$RE$EB0$RE$FA0$RR
[   ScriptRuntime] [  LOG] [08:48:38] [Test]  Text::OpenplanetFormatCodes: \$FF8\$SB\$EF0$RE\$EB0$RE\$FA0$RR
```

## Links

* User profile: https://trackmania.io/#/player/bc9b7c1c-1f54-4c47-9315-1ec880db90ca
* Club: https://trackmania.io/#/clubs/70766/summary

**Comment by Fort-TM** [comment]
Found another case while playing MP4, if it helps. In this case, seems like the author name has an extra $ that the game doesn't render, while Openplanet does

![20241118122820_1](https://github.com/user-attachments/assets/cfc0600f-e7e9-4214-9ed1-241550757fa9)

Notice how the game renders the author name normally, while Grinding Stats on the top right includes a $ at the start. [The plugin just uses OpenplanetFormatCodes for this](https://github.com/drekdrek/grinding-stats/blob/66e3bdd2acc2bca67551e85e8133a538b2b3e8cf/src/Render.as#L109-L111) (also happens with StripFormatCodes)

* Full username: `$o$ $0f0 "Old" Big A`
* Map: https://tm.mania.exchange/maps/249014/a-lot-of-concrete-2

**Comment by codecat** [comment]
The rendering of these are now fixed:
![image](https://github.com/user-attachments/assets/3172f0e3-1919-407b-a9dd-d0e728d69cab)
No changes were made to the mentioned functions.
