### ISSUE TITLE
No UI in Turbo on Linux

### ISSUE THREAD

**Issue by Atemu** [openplanet-nl/openplanet-issues#609]
On Linux, OpenPlanet for Turbo loads fine and plugins take effect but the UI does not function. OpenPlanet works as expected in ManiaPlanet and 2020 though.

[According to another penguin on the Discord](https://discord.com/channels/276076890714800129/449983875586850827/1315351742975574137), this used to work "a few months ago". It never worked for me but my first attempt was on 2024-10-14.

```
[        Platform] [  LOG] [00:17:29]  Openplanet for TrackMania Turbo x86
[        Platform] [ TRAC] [00:17:29]  (c) Melissa Geels 2016 - 2023
[        Platform] [ TRAC] [00:17:29]  https://openplanet.dev/
[        Platform] [  LOG] [00:17:29]  Openplanet starting on 2024-12-10
[        Platform] [  LOG] [00:17:29]  Engine: 2016-11-07 16:15:45
[        Platform] [  LOG] [00:17:29]  Openplanet: 1.27.2 (turbo, Public, 2024-10-01)
[        Platform] [ TRAC] [00:17:29]  Identifier: 0x0000000058209AA1
[        Platform] [ TRAC] [00:17:29]  Process ID: 1072
[        Platform] [  LOG] [00:17:29]  Setting up hook callbacks...
[        Platform] [  LOG] [00:17:30]  Semi entry initialization...
[        Platform] [  LOG] [00:17:30]  Requesting app config with timeout 5000...
[        Platform] [  LOG] [00:17:30]  Finding game window..
[        Platform] [ TRAC] [00:17:30]  Window handle: 0003013e ("TrackmaniaTurbo")
[        Platform] [  LOG] [00:17:30]  Update branch: default
[        Platform] [  LOG] [00:17:30]  Initializing meta...
[        Platform] [  LOG] [00:17:40]  Loop entry initialization...
[        Platform] [  LOG] [00:17:40]  Hooking WndProc...
[        Platform] [ TRAC] [00:17:40]  Initializing sockets...
[        Platform] [ TRAC] [00:17:40]  Adding user library path...
[        Platform] [  LOG] [00:17:40]  Initializing audio...
[           Audio] [  LOG] [00:17:40]  Setting playback device to "PulseAudio Output"
[        Platform] [  LOG] [00:17:40]  Initializing scripting...
[    ScriptEngine] [  LOG] [00:17:40]  Registered 1391 classes
[        Platform] [ TRAC] [00:17:41]  Writing type definitions to file: "C:\users\steamuser/OpenplanetTurbo/Openplanet.h"
[        Platform] [  LOG] [00:17:41]  Writing json to file: "C:\users\steamuser/OpenplanetTurbo/OpenplanetTurbo.json"
[        Platform] [  LOG] [00:17:41]  Dumping Openplanet documentation to C:\users\steamuser/OpenplanetTurbo/OpenplanetCore.json
[        Platform] [  LOG] [00:17:41]  Initializing overlay...
[         Overlay] [  LOG] [00:17:41]  Loading user style: Z:\Volumes\Games\Steam\steamapps\common\Trackmania Turbo\Openplanet/DefaultStyle.toml
[        Platform] [  LOG] [00:17:41]  Beginning script engine...
[    ScriptEngine] [  LOG] [00:17:41]  Adding plugins...
[    ScriptEngine] [ TRAC] [00:17:41]  TurboSkillpoints.op/:/Main.as (74, 1) : INFO : Compiling void RenderInterface()
[    ScriptEngine] [ WARN] [00:17:41]  TurboSkillpoints.op/:/Main.as (96, 24) : WARN : Float value truncated in implicit conversion to integer
[    ScriptEngine] [ WARN] [00:17:41]  TurboSkillpoints.op/:/Main.as (108, 53) : WARN : Signed/Unsigned mismatch
[    ScriptEngine] [ TRAC] [00:17:41]  TurboSkillpoints.op/:/Main.as (464, 1) : INFO : Compiling string PadNumber(int, uint)
[    ScriptEngine] [ WARN] [00:17:41]  TurboSkillpoints.op/:/Main.as (470, 24) : WARN : Signed/Unsigned mismatch
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded zipped plugin 'TurboSkillpoints' (version 1.0.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded zipped plugin 'SkipTurboIntro' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded zipped plugin 'EnableVR' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded plugin 'VehicleState' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded plugin 'PluginManager' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded plugin 'Discord' (version 1.0)
[    ScriptEngine] [  LOG] [00:17:41]  Adding legacy plugins...
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_BigDecor' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_Cameras' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_Customization' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_EditorDeveloper' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_HelloWorld' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_InfiniteEmbedSize' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_MapTools' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_StadiumUnlock' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_ToggleGhost' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_ToggleUI' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_TurboClassicEditor' (version 1.0)
[    ScriptEngine] [ TRAC] [00:17:41]  Loaded legacy plugin 'Plugin_TurboSTM' (version 1.0)
[    ScriptEngine] [  LOG] [00:17:41]  Plugins added!
[        Platform] [  LOG] [00:17:41]  Initialized!
[   ScriptRuntime] [ WARN] [00:17:41] [TurboSkillpoints]  Unable to open json file 'C:\users\steamuser/OpenplanetTurbo/PluginStorage/TurboSkillpoints/CachedSkillpoints.json'
[   ScriptRuntime] [ TRAC] [00:17:41] [PluginManager]  Checking for plugin updates..
[   ScriptRuntime] [  LOG] [00:17:41] [Discord]  Initializing Discord...
[   ScriptRuntime] [ TRAC] [00:17:41] [PluginManager]  No plugin updates found!
[   ScriptRuntime] [  LOG] [00:17:41] [Plugin_StadiumUnlock]  Automatically setting Stadium unlock patch for pack: TMTurbo@nadeolabs
[   ScriptRuntime] [  LOG] [00:17:41] [Plugin_StadiumUnlock]  Patched! Backup: "75"
[   ScriptRuntime] [  LOG] [00:17:41] [Plugin_StadiumUnlock]  Patched! Backup: "75"
[   ScriptRuntime] [  LOG] [00:17:41] [Plugin_StadiumUnlock]  Patched! Backup: "75"
[        Platform] [  LOG] [00:20:13]  Game is cleanly shutting down
[        Platform] [  LOG] [00:20:13]  Saving settings
[           Audio] [  LOG] [00:20:13]  Shutting down audio engine
[    ScriptEngine] [  LOG] [00:20:13]  Stopping script engine
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_TurboSTM'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_TurboClassicEditor'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_ToggleUI'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_ToggleGhost'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_StadiumUnlock'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_MapTools'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_InfiniteEmbedSize'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_HelloWorld'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_EditorDeveloper'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_Customization'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_Cameras'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Plugin_BigDecor'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'Discord'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'PluginManager'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'VehicleState'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'EnableVR'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'SkipTurboIntro'
[    ScriptEngine] [ TRAC] [00:20:13]  Unloading plugin 'TurboSkillpoints'
[    ScriptEngine] [  LOG] [00:20:13]  Releasing script context
[        Platform] [  LOG] [00:20:14]  Saving settings
[           Audio] [  LOG] [00:20:14]  Shutting down audio engine
[    ScriptEngine] [  LOG] [00:20:14]  Stopping script engine
[    ScriptEngine] [  LOG] [00:20:14]  Releasing script context
[        Platform] [  LOG] [00:20:14]  Terminating Openplanet..
[           Audio] [  LOG] [00:20:14]  Shutting down audio engine
```

My stack:

- Steam using GE-Proton9-19-3-gec2fa8a9
- NixOS 25.05 userspace (https://github.com/Atemu/nixpkgs/commit/b43e12f1d8182eb36c460d871a14f5678cb723bf, https://github.com/Atemu/nixos-config/commit/268e7e438ae5b9d28d4deb9e25d3d6d6dee97fb3)
- Hyprland compositor v0.45.2-b
- RADV Vulkan driver from mesa 24.2.6
- Linux 6.11.11
- NAVI21 GPU

Initial report in the Discord channel: 

https://discord.com/channels/276076890714800129/276076890714800129/1295236579576512615
https://discord.com/channels/276076890714800129/449983875586850827/1295476640721408060

**Comment by codecat** [comment]
Is this using DXVK, or something else? I seem to remember someone having similar problems on Mac, which were solved when switching to DXVK.

**Comment by Atemu** [comment]
Yes, DXVK is used by default with Proton. It's pretty much the exact same setup for ManiaPlanet and TM2020 and it works there which makes this doubly confusing.

**Comment by Atemu** [comment]
I'll try some older OP versions to see whether this is a regression in OP.

**Comment by Atemu** [comment]
Tried 1.26.14 and 1.25.45 but no dice.

**Comment by daih27** [comment]
I'm the "another penguin" mentioned. I tried looking at the proton logs with no success. Then, after trying some things that didn't work either, I started trying older proton versions. I tried first with GE-Proton8-27 and it indeed worked. So, many minutes later and a lot of brute-forcing, I concluded that the last version that works with Openplanet is GE-Proton9-7. I don't know the specific of what changed between GE-Proton9-7 and GE-Proton9-8, but here it is the comparison if it helps debugging the issue:

Comparison between GE-Proton9-7 and GE-Proton9-8: https://github.com/GloriousEggroll/proton-ge-custom/compare/GE-Proton9-7...GE-Proton9-8

Also, I tried Proton 9.0-4 downloaded from Steam and it didn't work either.

Anyway, I'm happy to help with more information if needed!

**Comment by Atemu** [comment]
Thank you so much, that's extremely valuable information!

I attempted to "bisect" the regular Proton version but that was stopped quickly as the current incarnation of the Ubisoft Connect launcher crap does is not supported by Proton <= 8. Didn't think to try Proton-GE versions.

So this is looking a lot like a WINE regression rather than an OpenPlanet issue directly. It might be OpenPlanet doing something weird but I find a WINE regression more likely.

Another member of the discord rightfully pointed out that TM Turbo is 32bit-only which very likely has something to do with this issue as all the other games are 64bit and everything works fine in those. I'll propagate this information and the fact that this is likely a WINE/Proton regression back to the Proton tracking issue.

I've been meaning to look into compiling Proton-GE myself for another purpose too lately, perhaps I could bisect this. Having a working baseline version is critical to doing this. We shouldn't wait too long to do this though as we don't know how long GE-Proton9-7 still works with Ubisoft Connect.

I'll take a closer look at the upstream WINE changes pulled into GE-Proton9-8; perhaps something pertaining 32bit or whatever d3d overlay mechanism OpenPlanet uses jumps out. (I'd love to know which it is, I have absolutely no expertise regarding d3d.)

**Comment by codecat** [comment]
Thanks for troubleshooting this! My guess is it's something in the dxvk changes.

**Comment by Atemu** [comment]
I've bisected it and it is indeed WINE: https://github.com/ValveSoftware/wine/commit/d9e2631cfd11ef2a11a964183d45847625be575d

I have little knowledge here but, in my mental model, making memory writeable should not cause issues for programs, only the opposite. I find it likely that the address logic is faulty when 32b but I'm not experienced enough to tell.

**Comment by codecat** [comment]
Thanks for finding the exact commit! I'll see if there's anything I can do here, and otherwise I guess you'll have to wait for the Wine folks to get back to you.

**Comment by codecat** [comment]
I believe this is a problem with Wine (using `WriteProcessMemory` on 32 bit builds w/o first calling `VirtualProtectEx` to make it writable has historically always worked). I'm not sure what the exact problem is; old protection of the memory we are writing is `PAGE_EXECUTE_READ`, so the linked commit should in theory work.

We were calling `VirtualProtectEx` on 64 bit builds, but not 32. As an experiment, I've now changed this to also happen on 32 bit builds. This might solve the problem.

Will be in the next `edge` build for Turbo. When that comes out (later today), let me know if that fixes it. Also, might be worth passing this information off to the Valve Wine folks.

**Comment by Atemu** [comment]
Oh my, thank you! Will try that.

I've relayed this info in the Proton thread already. I don't know of a better method to reach them unfortunately.

**Comment by codecat** [comment]
[1.27.4](https://openplanet.dev/download/version/273) is now on `edge`. Let me know if that fixes the problem.

**Comment by daih27** [comment]
If it's still needed, I can test in about 9 hours from now. Thank you very much!

**Comment by daih27** [comment]
I can confirm it's working with latest Proton 9.0-4 from Steam and proton-cachyos, which is the one I'm currently using.

**Comment by Atemu** [comment]
I can confirm it's indeed fixed!

Thank you so much @codecat, Openplanet support is ++ :)

**Comment by codecat** [comment]
Awesome, thank you for confirming!

**Comment by jolty1** [comment]
I can't seem to get Openplanet to work with Turbo at all, I have tried Edge 1.27.4/5 in Proton 9.0-4 and GE Proton 9.7 (also with non-edge and some older builds) but it looks like Openplanet.dll won't even load with module error 317. So I am not having the same success as others.

This doesn't happen in MP4/TM2020 as it just works.

[14:45:22] Starting on 2024-12-26
[14:45:22] Finding libs path
[14:45:22] Updating PATH to add: 'Z:\home\chris\.local\share\Steam\steamapps\common\Trackmania Turbo\Openplanet\Lib'
[14:45:22] Attaching DLL to: 'Z:\home\chris\.local\share\Steam\steamapps\common\Trackmania Turbo\TrackmaniaTurbo.exe'
[14:45:22] Failed to load Openplanet module, error 317
[14:45:22] Module handle: 00000000
[14:45:23] DirectInput8Create
[14:45:23] Openplanet.dll is not loaded yet!
[14:45:23] Couldn't find DinputInit function!

**Comment by codecat** [comment]
Error 317 is `ERROR_MR_MID_NOT_FOUND`, which I believe may happen in `FormatError`, so some other error is probably at fault here. I assume you don't have an `Openplanet.log` in `C:\Users\Username\OpenplanetNext`?

**Comment by jolty1** [comment]
In ~/.local/share/Steam/steamapps/compatdata/375900/pfx/drive_c/users/steamuser/OpenplanetTurbo/

I have an OpenplanetTurbo folder with a log in which is just

[        Platform] [  LOG] [15:16:02]  Openplanet for TrackMania Turbo x86

**Comment by Atemu** [comment]
You're experiencing an entirely separate issue then. In this issue OpenPlanet would load and work but not show the UI.

I'd prefer you open a separate issue.
