### ISSUE TITLE
Expose additional DrawList methods for lines/curves

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#610]
There are some methods on UI::DrawList that aren't exposed that would be nice to have:

* `ImDrawList::AddBezierCubic`
* `ImDrawList::AddBezierQuadratic`
* `ImDrawList::AddPolyline`

**Comment by codecat** [comment]
I've added the bezier curve functions, but Polyline is a bit more difficult. I can make a naive implementation, but that involves allocation so it would make calling the function very expensive. How badly do you need this function?

**Comment by XertroV** [comment]
Not badly. The bezier methods are most useful (I wanted one of those, and saw there was polyline too)
