### ISSUE TITLE
ternary returning either a `Json::Value@` or `null` crashes game

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#613]
```Angelscript
auto item = true ? Json::Object() : null;
```
The line above crashes the game reliably with this error:

![Screenshot 2024-12-14 170426](https://github.com/user-attachments/assets/099343a6-b85a-4928-91e5-f43994676816)

**Comment by codecat** [comment]
Can you report this on the Angelscript forum? https://gamedev.net/forums/forum/34-angelcode/

**Comment by codecat** [comment]
Reproducable code for the Angelscript report:
```asc
class @Thing {
  int opImplConv() const { return 0; }
  float opImplConv() const { return 0; }
}
void Main() {
  auto foo = true ? Thing() : null;
}
```

**Comment by ezio416** [comment]
issue is with angelscript, not openplanet
https://gamedev.net/forums/topic/717777-opimplconv-with-different-return-types-crashes-application-in-ternary-operator-assignment/
