### ISSUE TITLE
`await(coro)` will block forever if `coro` is already done.

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#618]
If you start a coro, do some other stuff, then come back and `await(coro)`, you need to check if `coro.IsRunning()` first, because if it's not `await` never returns.

I feel like this should basically be a noop instead, like `await(coro)` should return immediately if the coro isn't running.

**Comment by codecat** [comment]
Agreed

**Comment by codecat** [comment]
I couldn't reproduce the specific issue you mentioned, but it looks like `await()` with a single coroutine got broken during a refactor some time ago, which is probably what you're running into. This has now been fixed.
