### ISSUE TITLE
`SortDirection` for tables returns wrong values in Turbo

### ISSUE THREAD

**Issue by Fort-TM** [openplanet-nl/openplanet-issues#620]
When checking `SortDirection` for a TableSortSpecs spec on Turbo,  it will return garbage values like  `-1959888383`  instead of the ones corresponding to the enum `UI::SortDirection`

This issue is only present in Turbo, since it works correctly on TMNEXT / MP4

**Comment by codecat** [comment]
It's kind of a surprise to me that it works on the other games. It probably works by pure chance. This is fixed now, thank you for spotting this!
